<a href="https://colab.research.google.com/github/rnwjdgus03/NLP_05-Team-Project-3/blob/Category-Extension/article_combined_pipeline_colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 기사 통합 추출 파이프라인 (Colab) — is_claim 판별 + 컬럼 추출 동시 처리

`extract_article_claims_hcx.py` 하나로 기사 전체를 처리합니다.

```
articles.csv (기사 본문 전체)
   ↓ extract_article_claims_hcx.py
   기사 전체를 HCX에 통째로 넣어
     1) 검증 가능한 claim 문장을 찾고 (is_claim 판별)
     2) 동시에 그 문장의 수치/통계 컬럼을 추출              ← API 호출
최종 데이터셋 (hcx_article_extracted.csv)
```

문장 단위로 나눠서 처리하는 이전 버전(`article_to_claims.py` → `is_claim_filter_hcx.py`
→ `filter_true_claims.py` → `extract_hcx.py`)과 달리, 기사 전체 맥락(제목·다른 문단 포함)을
보고 판단하기 때문에 시점(period)처럼 문장 하나만으로는 알 수 없는 정보를 더 잘 채울 수
있습니다. 대신 기사(또는 chunk) 하나당 API 호출이 크고 무거우니, 처음엔 `LIMIT`을 작게
두고 결과를 확인한 뒤 늘리세요. 중단 후 재실행하면 이미 처리한 기사(article_id)는 건너뛰고
이어서 처리됩니다.

## 0. 준비물

- 스크립트 2개: `extract_hcx.py`, `extract_article_claims_hcx.py`
  (`extract_article_claims_hcx.py`가 `extract_hcx.py`의 검증/보정 함수를 그대로 불러써서
  두 파일 모두 필요합니다.)
- 기사 원문 CSV: `article_id, title, date, url, body` 칼럼 (body = 기사 본문 전체 텍스트)
- Colab 보안 비밀(Secrets)에 `CLOVA_API_KEY` 등록
  - 왼쪽 사이드바 🔑(보안 비밀) 아이콘 → "새 보안 비밀 추가"
  - 이름: `CLOVA_API_KEY`, 값: 발급받은 키, **"노트북 액세스" 토글 켜기**

In [ ]:
# 필요한 패키지 설치
!pip install -q requests python-dotenv

In [ ]:
!python is_claim_filter_hcx.py --input all_sentences_51_100.csv --output is_claim_result.csv
# python filter_true_claims.py --input is_claim_result.csv --output claims_filtered.csv
# python extract_hcx.py --input claims_filtered.csv --output hcx_extracted.csv

[B0001-s000] False (hcx) 현재 문장은 특정 전문가의 의견 및 예측을 담고 있으며, 이는 KOSIS
[B0001-s001] True (hcx) 현재 문장은 올해 서울, 경기도 및 지방의 집값 상승 및 하락 예측을 포
[B0001-s002] False (hcx) 탄핵 정국이 환율 급등, 공사비 인상, 분양가 상승 등의 영향을 미칠 것
[B0001-s003] False (hcx) 현재 문장은 부동산 전문가의 의견 및 예측을 담고 있으며, 구체적인 수치
[B0001-s004] False (hcx) 현재 문장은 질문 형태로 되어 있으며, 특정한 수치나 통계적인 변화를 주
[B0001-s005] False (hcx) 현재 문장은 서울과 수도권의 부동산 가격 상승에 대한 예측이므로, 이는
[B0001-s006] False (hcx) 현재 문장은 수도권 내 특정 지역의 부동산 가격 상승 예측에 대한 의견을
[B0001-s007] True (hcx) 현재 문장은 '나머지 지역은 조금 떨어질 수도 있을 것이라고 본다.'라는
[B0001-s008] True (hcx) 현재 문장은 서울의 집값이 2~3% 정도 상승할 것이라는 구체적인 수치적
[B0001-s009] True (hcx) 경기도의 외곽 지역에서 하락 가능성을 언급하며 전체적으로 1~2% 정도의
[B0001-s010] True (hcx) 지방의 부동산 가격 변동에 대한 예측이므로 국내 집계 통계로서 KOSIS
[B0001-s011] False (hcx) 현재 문장은 수도권 주택 공급이 줄고 있다는 일반적인 상황을 언급하지만,
[B0001-s012] False (hcx) 현재 문장은 '공급 부족은 가격 상승에 가장 큰 원인이다.'라는 단순한
[B0001-s013] False (hcx) 현재 문장은 다주택자들의 물건 출회와 관련된 정책에 대한 의견을 제시하지
[B0001-s014] False (hcx) 현재 문장은 정치적 불확실성이 부동산 가격에 미치는 영향에 대한 의견이지
[B0001-s015] False (hcx) 정치적 불확실성이 큰 변수라는 단순한 의견 표현이므로, 이는 KOSIS
[B0001-s016] False (hcx) 환율의 급격한 상승에 대한 구체적인 수치나 비율이 제공되지 않으며, 이는
[B0001-s017] False (hcx) 환율이 오르면 수입 건설 원자재 가격이 상승한다는 주장은 단순한 원인과
[B0001-s018] False (hcx) 현재 문장은 '공사비에 영향을 주고, 분양가가 인상 압박을 받는다.'라는
[B0001-s019] False (hcx) 현재 문장은 가격 상승의 가능성을 언급하지만 구체적인 수치나 통계적인 변
[B0001-s020] True (hcx) 문장에서 '아파트 신규 입주 물량이 줄어든다'라는 내용이 있으며 이는 국
[B0001-s021] False (hcx) 현재 문장은 부동산 정책에 대한 일반적인 의견을 묻는 질문이므로, 수치나
[B0001-s022] False (hcx) 현재 문장은 주택 공급 정책에 대한 일반적인 의견을 제시하며, 특정한 수
[B0001-s023] False (hcx) 현재 문장은 1기 신도시 재건축 및 그린벨트 해제에 대한 정책적 의견을
[B0001-s024] False (hcx) 현재 문장은 서울 외곽의 그린벨트 해제와 관련된 정책에 대한 의견을 제시
[B0001-s025] False (hcx) 현재 문장은 정책 변화에 대한 평가 및 중요성에 대해 언급하고 있으며,
[B0001-s026] False (hcx) 현재 문장은 부동산 세금 정책에 대한 변화에 대해 언급하지만, 이는 특정
[B0001-s027] False (hcx) 현재 문장은 공시지가 및 종합부동산세에 대한 언급이지만, 구체적인 수치나
[B0001-s028] False (hcx) 현재 문장은 특정 정책에 대한 의견과 우려를 표현하고 있으며, 이는 단순
[B0001-s029] False (hcx) 현재 문장은 수요자들의 대처 방안에 대한 질문이지, 수치나 통계적인 변화
[B0001-s030] False (hcx) 현재 문장은 무주택자와 유주택자의 전략 차이에 대한 조언이지, 구체적인
[B0001-s031] True (hcx) 현재 문장은 '올해 집값이 떨어진다고 보기는 어렵다.'라는 내용으로, 이
[B0001-s032] False (hcx) 현재 문장은 서울 및 수도권 주요 지역의 부동산 가격 상승 예측에 대한
[B0001-s033] False (hcx) 현재 문장은 부동산 시장의 거래량 감소 및 매수자 우위 시기에 대한 일반
[B0001-s034] False (hcx) 현재 문장은 부동산 매수 시점에 대한 조언으로, 특정한 수치나 통계적인
[B0001-s035] False (hcx) 현재 문장은 특정 서비스나 기능에 대한 광고성 내용으로, 수치나 통계적인
[B0001-s036] False (hcx) 현재 문장은 다주택자에 대한 세금 규제 변화에 따른 리스크를 언급하지만,
[B0001-s037] False (hcx) 현재 문장은 금리 변화에 따른 부동산 시장의 일반적인 전망을 담고 있으며
[B0001-s038] False (hcx) 현재 문장은 금리 변화에 따른 수요자들의 행동에 대한 예측이므로, 이는
[B0001-s039] False (hcx) 현재 문장은 지방의 부동산 상황에 대한 일반적인 서술로, 특정한 수치나
[B0001-s040] False (hcx) 현재 문장은 법인 임대사업자와 다주택자의 주택 취득세율에 대한 정보 제공
[B0001-s041] False (hcx) 현재 문장은 특정 정책에 대한 필요성을 언급하지만, 이는 단순한 의견 평
[B0001-s042] False (hcx) 현재 문장은 지방 아파트를 사서 임대 사업을 할 수 있도록 환경을 조성해
[B0001-s043] False (hcx) 현재 문장은 세제 지원 필요성에 대한 의견을 표현하고 있으며, 이는 단순
[B0001-s044] False (hcx) 현재 문장은 지방 미분양 해소에 대한 단순한 의견 표현이므로, KOSIS
[B0001-s045] False (hcx) 현재 문장은 특정 상황에 대한 설명이지만, 수치나 통계적인 변화를 주장하
[B0001-s046] True (hcx) 문장에서 '공급이 줄어들기 때문에 결국엔 가격이 오르게 된다.'라는 내용
[B0001-s047] False (hcx) 현재 문장은 '미분양이 심각해도 장기적으로 볼 때 가격을 끌어올리는 방향
[B0002-s000] False (hcx) 문장은 우주 탐사에서 AI의 역할에 대한 일반적인 설명을 포함하지만, 구
[B0002-s001] False (hcx) 국제우주정거장에서 AI 승무원이 어떤 역할을 한다는 것은 단순한 정보 제
[B0002-s002] False (hcx) 현재 문장은 사이먼2가 사이먼의 후속 모델이라는 정보를 전달하지만, 이는
[B0002-s003] False (hcx) 현재 문장은 사이먼2라는 AI 승무원이 우주 비행사와 상호작용하며 다양한
[B0002-s004] False (hcx) 현재 문장은 우주 비행사의 감정 상태를 분석하여 노래나 대화를 제공하는
[B0002-s005] False (hcx) 현재 문장은 NASA가 심우주 탐사에 AI 의사를 투입하려는 계획을 언급
[B0002-s006] False (hcx) 현재 문장은 우주 비행사들의 건강을 모니터링하기 위해 AI 의사를 배치한
[B0002-s007] False (hcx) 현재 문장은 우주 개발에 있어서 AI의 중요성을 언급하지만, 구체적인 수
[B0002-s008] True (hcx) 화성에 있는 이동형 탐사 로봇 퍼서비어런스가 AI를 활용해 표면 암석을
[B0002-s009] False (hcx) 현재 문장은 AI의 기능 및 역할에 대한 기술적 설명을 포함하고 있으며,
[B0002-s010] False (hcx) 현재 문장은 우주선의 이착륙과 운항에서 AI 역할이 커진다는 일반적인 서
[B0002-s011] False (hcx) 현재 문장은 스페이스X가 우주선 운항을 AI로 최적화한다는 내용이지만,
[B0002-s012] False (hcx) 연료 사용 효율 및 최적 항로에 대한 AI의 기여도를 언급하지만, 이는
[B0002-s013] False (hcx) 현재 문장은 우주 쓰레기를 회피하는 데 AI가 활용된다는 일반적인 설명을
[B0002-s014] False (hcx) 현재 문장은 우주선과 위성의 AI 기능에 대한 기술적 설명을 포함하지만,
[B0002-s015] False (hcx) 현재 문장은 NASA의 모의 화성 거주지가 AI 분석을 통해 설계되었다는
[B0002-s016] False (hcx) 온도와 습도 등의 실시간 환경 측정과 조정, 모의 거주 실험 참가자들의
[B0003-s000] False (hcx) 현재 문장은 의대 학생들의 휴학 관련 내용으로, 수치나 통계적인 변화를
[B0003-s001] False (hcx) 현재 문장은 의대 학생들의 휴학 관련 결정을 전달하는 내용으로, 수치나
[B0003-s002] False (hcx) 현재 문장은 의대생들의 휴학 관련 결정을 전달하는 내용으로, 수치나 통계
[B0003-s003] False (hcx) 현재 문장은 의대생의 투쟁 방식에 대한 내용으로, 수치나 통계적인 변화를
[B0003-s004] False (hcx) 현재 문장은 의대생 단체의 투쟁 방침에 관한 내용으로, 수치나 통계적인
[B0004-s000] False (hcx) 현대차그룹의 미국 시장 실적 관련 정보는 특정 기업의 매출 및 판매량에
[B0004-s001] True (hcx) 현대차그룹의 미국 시장 판매량 및 현대차의 판매량이 구체적으로 언급되어
[B0004-s002] True (hcx) 현대차그룹의 미국 시장에서의 판매량 증가를 구체적인 수치와 함께 제시하고
[B0004-s003] True (hcx) 현대차의 판매량이 전년 대비 4.8% 증가했다는 구체적인 수치와 비교를
[B0004-s004] True (hcx) 현대차와 제네시스의 판매량이 2023년에 비해 각각 4.4%, 8.5%
[B0004-s005] True (hcx) 현대차, 기아, 제네시스가 2023년의 실적을 초과하여 역대 최고 판매량
[B0004-s006] False (hcx) 현대차와 기아의 SUV 및 친환경차의 판매 호조에 대한 정보는 구체적인
[B0004-s007] True (hcx) 현대차의 전기차 아이오닉5와 대형 SUV 팰리세이드의 판매량이 각각 31
[B0004-s008] True (hcx) 현재 문장은 기아의 다양한 차종의 판매량이 역대 최대라는 내용을 포함하고
[B0004-s009] True (hcx) 미국 시장에서 현대차그룹의 판매량이 다른 자동차 제조사들과 비교되어 언급
[B0004-s010] False (hcx) 현재 문장은 미국 시장에서의 자동차 제조사들의 판매량을 나열하고 있으며,
[B0005-s000] False (hcx) 문장은 특정 기업의 퇴직직원 동우회 통합 관련 내용으로, 수치나 통계적
[B0005-s001] False (hcx) 현재 문장은 금융기관 간의 합병 및 그에 따른 동우회의 통합에 대한 내용
[B0005-s002] False (hcx) 현재 문장은 두 은행의 퇴직 직원 동우회가 통합된다는 내용으로, 이는 수
[B0005-s003] False (hcx) 현재 문장은 우리은행의 퇴직직원 동우회에 대한 역사적 배경 및 그 목적에
[B0005-s004] False (hcx) 현재 문장은 우리은행의 내부 운영 방식 및 동우회의 변화에 대한 설명이므
[B0005-s005] False (hcx) 현재 문장은 우리은행 내부의 계파 문화 및 그로 인한 문제점에 대한 의견
[B0005-s006] False (hcx) 임종룡 우리금융회장의 취임 및 그의 발언 내용은 특정 사건이나 인물 관련
[B0005-s007] False (hcx) 현재 문장은 임종룡 회장의 발언 및 행동에 대한 내용으로, 이는 단순한
[B0005-s008] False (hcx) 현재 문장은 우리은행 관계자의 발언으로, 이는 단순한 의견 표현이지 수치
[B0005-s009] False (hcx) 현재 문장은 통합된 우리은행 동우회장을 어떻게 선출할 것인지에 대한 내용
[B0005-s010] False (hcx) 현재 문장은 우리은행 관계자의 발언으로서, 구체적인 수치나 통계적 변화를
[B0005-s011] False (hcx) 현재 문장은 우리금융이 인사 자료에서 출신 은행 구분 정보를 삭제한다는
[B0006-s000] False (hcx) 문장에서 언급된 내용은 주로 소매업체들이 설 선물 예약 판매 및 기획 세
[B0006-s001] True (hcx) 설 선물 세트를 미리 구매한 소비자의 수가 작년보다 대폭 늘었다는 것은
[B0006-s002] True (hcx) 설선물 매출 증가율을 백화점별로 구체적으로 제시하며, 이는 KOSIS를
[B0006-s003] True (hcx) 현재 문장은 대형마트 3사의 매출이 지난 설과 비슷하다는 내용을 포함하며
[B0006-s004] False (hcx) 현재 문장은 신세계백화점이 2025년 설 선물세트를 예약 판매하는 기간에
[B0006-s005] True (hcx) 지난해 설 대비 10% 늘어난 5만여 세트를 예약판매 물량으로 준비했다는
[B0006-s006] False (hcx) 주어진 문장은 특정 상품들의 할인율을 나열하고 있으며, 이는 KOSIS에
[B0006-s007] False (hcx) 현재 문장은 현대백화점의 2025년 설 선물세트 예약 판매 일정에 대한
[B0006-s008] False (hcx) 현재 문장은 특정 점포 및 온라인 몰에서의 행사 일정과 관련된 정보로,
[B0006-s009] False (hcx) 현재 문장은 백화점 및 마트의 예약 판매 일정과 관련된 정보 제공이므로,
[B0006-s010] False (hcx) 현재 문장은 할인 판매되는 상품 종류 및 할인율에 대한 정보 제공이지만,
[B0006-s011] True (hcx) 롯데백화점의 설 사전 예약 판매 품목 및 할인율을 언급하며, 이는 KOS
[B0006-s012] False (hcx) 현재 문장은 마트 업계의 설 선물 사전 예약 상황에 대한 일반적인 정보
[B0006-s013] False (hcx) 현재 문장은 롯데마트의 주류 전문매장 보틀벙커와 함께하는 사전예약 프로모
[B0006-s014] False (hcx) 현재 문장은 특정한 수치나 비율 등의 변화를 주장하지 않으며, 단순한 상
[B0006-s015] True (hcx) 현재 문장은 '선물세트의 물량을 지난 설보다 약 30% 늘렸다.'라는 내
[B0006-s016] True (hcx) 롯데마트 관계자가 언급한 '와인 묶음 선물세트의 매출이 전년대비 20%
[B0006-s017] True (hcx) 현재 문장은 이마트의 과일 세트 주요 품목 가격이 전년보다 낮아졌다는 내
[B0006-s018] True (hcx) 사과 선물 세트 가격이 지난 설보다 약 10% 낮다는 것은 KOSIS 국
[B0006-s019] True (hcx) 샤인머스캣의 생산량 증가 및 가격 변동에 대한 정보는 국가통계포털(KOS
[B0006-s020] False (hcx) 현재 문장은 축산 및 수산 선물 세트의 가격대에 대한 정보를 제공하고 있
[B0006-s021] True (hcx) 홈플러스가 2만~6만 원대 중·저가 선물 세트 상품 수를 전년 대비 약
[B0006-s022] False (hcx) 현재 문장은 단순한 의견이나 평가로, 구체적인 수치나 통계적인 변화를 포
[B0006-s023] False (hcx) 특정 기업의 할인 혜택 제공 여부에 대한 내용으로, 이는 단순한 거래 조
[B0007-s000] False (hcx) 현재 문장은 보험산업의 경영 효율화와 유동성 모니터링 필요성에 대한 분석
[B0007-s001] False (hcx) 현재 문장은 보험산업의 성장 전망에 대한 의견을 제시하지만, 이는 구체적
[B0007-s002] False (hcx) 현재 문장은 보험산업의 성장 전망에 대한 의견을 제시하지만, 이는 구체적
[B0007-s003] False (hcx) 현재 문장은 금리 하락과 관련된 보험사의 대응 방안에 대한 설명이지만,
[B0007-s004] False (hcx) 현재 문장은 달러 강세와 관련된 환 헤지 전략에 대한 조언을 담고 있으며
[B0007-s005] True (hcx) 현재 문장은 한국의 경제성장률이 작년 대비 다소 하락하여 2% 수준이 될
[B0007-s006] True (hcx) 현재 문장은 '올해 말 국채 10년물 금리가 2% 중반대에 이를 것으로
[B0007-s007] False (hcx) 현재 문장은 보험회사의 새로운 회계제도와 관련된 내용으로, 구체적인 수치
[B0007-s008] False (hcx) 현재 문장은 보험부채평가 기준의 구체화와 관련된 내용으로, 이는 단순한
[B0007-s009] False (hcx) 현재 문장은 보험 모집에서의 경쟁 방식과 관련된 내용으로, 구체적인 수치
[B0007-s010] False (hcx) 현재 문장은 실손의료보험 개편 방안에 대한 제안으로, 구체적인 수치나 통
[B0007-s011] False (hcx) 현재 문장은 기술 및 트렌드에 관한 내용으로 보이며, 수치나 통계적 변화
[B0008-s000] False (hcx) 현재 문장은 새로운 회계제도에 대한 금융당국의 강조 사항에 관한 내용으로
[B0008-s001] False (hcx) 현재 문장은 금융감독원이 IFRS17 안정화와 관련된 내용을 발표한 것에
[B0008-s002] False (hcx) 현재 문장은 금융당국의 감독 방침에 관한 내용으로, 수치나 통계적인 변화
[B0008-s003] False (hcx) 현재 문장은 IFRS17과 관련된 금융당국의 조치와 계도 기간에 대해 설
[B0008-s004] False (hcx) 현재 문장은 보험개혁회의를 통한 보험회계 개선방안 발표에 관한 내용으로,
[B0008-s005] False (hcx) 현재 문장은 보험업계에서 공동협의체를 통한 회계 처리 방식에 대한 논의나
[B0008-s006] False (hcx) 현재 문장은 금융당국과 보험업계의 회계 처리 문제에 관한 내용으로, 특정
[B0008-s007] False (hcx) 현재 문장은 금감원의 계획과 관련된 내용으로, 수치나 통계적인 변화를 주
[B0008-s008] False (hcx) 현재 문장은 금융감독원의 회계 처리 방침과 관련된 내용으로, 구체적인 수
[B0009-s000] False (hcx) 현재 문장은 한국거래소의 시스템 개발 및 테스트 일정에 대한 내용으로,
[B0009-s001] False (hcx) 현재 문장은 거래소의 시스템 개발 및 테스트 일정에 대한 내용으로, 수치
[B0009-s002] False (hcx) 현재 문장은 공매도 전산시스템 개발 일정에 대한 설명이므로 수치나 통계적
[B0009-s003] False (hcx) 현재 문장은 공매도 전산시스템의 종류에 대한 설명으로, 수치나 통계적인
[B0009-s004] False (hcx) 현재 문장은 공매도 방지 시스템에 대한 설명으로, 수치나 통계적인 변화를
[B0009-s005] False (hcx) 현재 문장은 NSDS 시스템이 어떻게 작동하는지 설명하는 것으로, 수치나
[B0009-s006] False (hcx) 현재 문장은 거래 체결 후 3거래일이 소요된다는 내용으로, 이는 단순한
[B0009-s007] False (hcx) 현재 문장은 NSDS 시스템의 기능에 대한 설명으로, 수치나 통계적인 변
[B0009-s008] True (hcx) 문장에서 '이번 연계 테스트는 90% 이상의 공매도 거래 비중을 차지하는
[B0009-s009] False (hcx) 현재 문장은 시스템 개발 일정에 대한 내용으로, 수치나 통계적인 변화를
[B0009-s010] False (hcx) 현재 문장은 모의시장 운영 일정에 대한 정보 제공이지, 수치나 비율 등의
[B0009-s011] False (hcx) 현재 문장은 시스템의 안정화에 대한 계획과 관련된 내용으로, 특정한 수치
[B0009-s012] False (hcx) 현재 문장은 NSDS 개발 과정에서의 설명회 개최에 대한 내용으로, 수치
[B0009-s013] False (hcx) 현재 문장은 거래소가 NSDS 잔고 보고에 활용할 수 있는 상세 매뉴얼을
[B0009-s014] False (hcx) 현재 문장은 공매도 전산시스템 구축의 기대 효과에 대한 단순한 의견 표현
[B0009-s015] False (hcx) 코스피 코스닥 증권에 관한 정보는 특정한 수치나 통계적 변화를 주장하지
[B0010-s000] False (hcx) 문장은 은행 동우회의 명칭 변경 및 통합 관련 내용으로, 수치나 통계적인
[B0010-s001] False (hcx) 현재 문장은 우리은행의 창립 126주년 기념식과 관련된 내용으로, 수치나
[B0010-s002] False (hcx) 현재 문장은 행사 참석자들에 대한 정보 제공으로, 수치나 통계적 변화를
[B0010-s003] False (hcx) 현재 문장은 퇴직직원 동우회의 목적 및 성격에 대한 설명으로, 수치나 통
[B0010-s004] False (hcx) 현재 문장은 두 은행의 동우회가 합병 후에도 별도로 운영되었다는 역사적
[B0010-s005] False (hcx) 현재 문장은 우리은행에서 함께 근무한 직원들이 퇴직 후 출신은행별로 다른
[B0010-s006] False (hcx) 현재 문장은 우리금융그룹의 내부적인 변화에 대한 내용으로, 특정한 수치나
[B0010-s007] False (hcx) 현재 문장은 상업 및 한일 은행의 계파 문화가 은행 발전의 저해요인으로
[B0010-s008] False (hcx) 현재 문장은 우리은행 동우회의 통합 필요성에 대한 설명을 하고 있으며,
[B0010-s009] False (hcx) 현재 문장은 우리은행의 동우회 통합 과정에 대한 내용으로, 수치나 통계적
[B0010-s010] False (hcx) 현재 문장은 우리은행의 원로 은행장들과 퇴직 선배들이 후배들의 쇄신 노력
[B0010-s011] False (hcx) 현재 문장은 우리금융의 내부 정책 변경 및 문화 개선 계획에 대한 내용으
[B0011-s000] True (hcx) 작년 4분기 상장사들의 실적이 3개월 전보다 약 16.5% 낮아졌다는 내
[B0011-s001] False (hcx) 투자자들의 심리 변화에 대한 언급이지만, 이는 구체적인 수치나 통계적 변
[B0011-s002] True (hcx) 현재 문장은 삼성전자의 작년 4분기 영업이익 컨센서스가 8조4751억원으
[B0011-s003] True (hcx) 현재 문장은 삼성전자의 작년 4분기 영업이익이 직전년도 같은 기간 대비
[B0011-s004] False (hcx) 현재 문장은 실적 전망 및 목표주가 하향 조정과 관련된 내용으로, 이는
[B0011-s005] True (hcx) 코스피 상장사 110곳의 총 영업이익이 39조6531억원이라는 구체적인
[B0011-s006] True (hcx) 코스피 상장사의 4분기 영업이익이 이전 분기 대비 얼마나 변했는지 나타내
[B0011-s007] True (hcx) 현재 문장은 2023년 4분기와 2024년 4분기의 영업이익 합계를 비교
[B0011-s008] False (hcx) 현재 문장은 실적 하향 조정과 업종별 차별화에 대한 의견을 제시하지만,
[B0011-s009] True (hcx) 문장에서 '12월 수출이 예상치를 상회하는 호조를 보였다'라는 내용은 한
[B0011-s010] False (hcx) 현재 문장은 반도체 업황과 관련된 분석 의견을 제시하며, 이는 단순한 의
[B0011-s011] False (hcx) 현재 문장은 '#코스피 코스닥 증권'이라는 해시태그로, 어떠한 수치나 통
[B0012-s000] False (hcx) 문장은 장학재단의 장학생 모집 공고에 대한 내용으로, 수치나 통계적인 변
[B0012-s001] False (hcx) 현재 문장은 장학재단의 장학생 지원 혜택에 대한 내용으로, 특정한 수치나
[B0012-s002] False (hcx) 현재 문장은 장학금의 지급 조건 및 지원 내용에 대한 설명이지, 수치나
[B0012-s003] False (hcx) 현재 문장은 MBK장학재단의 가치와 관련된 내용으로, 수치나 통계적 변화
[B0012-s004] False (hcx) 현재 문장은 MBK 장학재단의 설립 목적 및 배경에 대한 설명이므로, 수
[B0012-s005] False (hcx) MBK장학재단을 통해 배출된 장학생 수는 특정 기관의 활동에 대한 정보이
[B0012-s006] False (hcx) 현재 문장은 교육의 중요성에 대한 의견을 표현하고 있으며, 이는 수치나
[B0012-s007] False (hcx) 현재 문장은 MBK 장학재단의 장학금 신청 관련 정보 제공에 관한 내용으
[B0012-s008] False (hcx) 코스피 코스닥 증권이라는 문장은 단순한 용어의 나열로, 수치나 비율 등의
[B0013-s000] False (hcx) 현재 문장은 OK금융그룹 오너 일가의 대부업체 청산에 대한 내용으로, 이
[B0013-s001] False (hcx) 현재 문장은 특정 개인이 소유한 대부업체들에 대한 정보 제공이므로, 이는
[B0013-s002] False (hcx) 현재 문장은 OK금융과 관련된 대부업체들이 문을 닫았다는 사실을 전달하지
[B0013-s003] False (hcx) OK홀딩스가 보유한 옐로우캐피탈이 대부업 라이선스를 반납하고 폐업했다는
[B0013-s004] False (hcx) OK홀딩스가 옐로우캐피탈 자산을 양수받아 청산 작업을 진행했다는 사실은
[B0013-s005] False (hcx) 특정 기업의 대부업체 청산에 대한 내용으로, 이는 KOSIS에서 다루는
[B0013-s006] False (hcx) 현재 문장은 특정 기업의 자산 매각 상황에 대한 내용으로, 이는 KOSI
[B0013-s007] False (hcx) OK금융의 대부업 철수에 대한 내용은 특정 기업의 사업 종료 상태를 나타
[B0013-s008] False (hcx) OK금융의 대부업 청산이 시작된 연도에 대한 정보는 단순한 역사적 사실로
[B0013-s009] False (hcx) OK금융이 예주·예나래저축은행 인수를 추진하는 과정에서 금융 당국이 대부
[B0013-s010] False (hcx) OK금융의 대부업 자산 단계적 축소 및 시장에서의 완전 철수에 대한 약속
[B0013-s011] False (hcx) OK금융이 원캐싱, 미즈사랑, 러시앤캐시를 단계적으로 청산했다는 사실은
[B0013-s012] False (hcx) 현재 문장은 OK금융의 자산 규모가 늘어난 것에 대한 단순한 서술로, 특
[B0013-s013] False (hcx) OK금융 자산 규모가 급격히 늘어났다는 내용은 수치나 비율 등의 구체적인
[B0013-s014] False (hcx) 현재 문장은 특정 기업의 구조 및 관계에 대한 설명이므로 KOSIS 통계
[B0013-s015] False (hcx) 현재 문장은 최호씨의 소유 구조 및 관계에 대한 설명으로, 수치나 통계적
[B0013-s016] False (hcx) 현재 문장은 금융 당국의 조치에 대한 설명으로, 특정한 수치나 통계적인
[B0013-s017] False (hcx) 현재 문장은 OK금융의 대부업 청산과 상상인저축은행 인수에 대한 예측 및
[B0013-s018] False (hcx) OK금융이 상상인저축은행 실사를 마치고 인수 조건을 검토 중이라는 내용은
[B0013-s019] True (hcx) 상상인저축은행 매각가가 자본금 수준인 3000억원 내외라는 구체적인 금액
[B0014-s000] False (hcx) 지난해 하반기 증시 부진으로 공모주 시장이 얼어붙었다는 내용은 일반적인
[B0014-s001] True (hcx) 현재 문장은 지난해 상반기에 공모주 펀드에 유입된 자금 총액을 명시하며,
[B0014-s002] True (hcx) 문장에서 하반기에 공모주 펀드에서 자금 유출이 발생했다고 언급하며, 이는
[B0014-s003] False (hcx) 현재 문장은 공모주 시장의 위축과 그로 인한 자금 이동에 대한 해석이므로
[B0014-s004] False (hcx) 현재 문장은 지난해 상반기에 상장된 기업들이 최종 공모가를 어떻게 설정했
[B0014-s005] True (hcx) 문장에서 '하지만 하반기 상장한 48개 기업 중 12개 기업은 희망 범위
[B0014-s006] False (hcx) 현재 문장은 공모가가 희망 범위에 미달한 기업의 수와 분기 정보를 제공하
[B0014-s007] False (hcx) 현재 문장은 특정 기업의 상장 철회 및 일정 연기에 대한 내용으로, KO
[B0014-s008] False (hcx) 현재 문장은 2024년 기업공개(IPO) 시장의 일반적인 흐름에 대한 설
[B0014-s009] False (hcx) 현재 문장은 공모가의 희망 범위 미달 및 시장 상황에 대한 설명을 포함하
[B0014-s010] False (hcx) 현재 문장은 올해 상반기부터 공모 규모가 큰 대기업들이 상장하면서 공모주
[B0014-s011] False (hcx) 현재 문장은 대기업들이 상장 채비를 하고 있다는 내용이지만, 구체적인 수
[B0014-s012] False (hcx) 현재 문장은 LG CNS 및 다른 회사들의 상장 계획에 대한 정보를 제공
[B0014-s013] False (hcx) 코스피 코스닥 증권이라는 문장은 단순한 용어의 나열로, 수치나 비율 등의
[B0015-s000] False (hcx) 현재 문장은 신한은행장의 발언 내용으로, 단순한 의견 표현 및 전략 강조
[B0015-s001] False (hcx) 현재 문장은 신한은행의 경영 전략 및 변화에 대한 내용으로, 특정한 수치
[B0015-s002] False (hcx) 현재 문장은 단순한 의견이나 평가로서, 통계값이나 통계적 변화 방향에 관
[B0015-s003] False (hcx) 현재 문장은 리더십과 도덕적 기준에 대한 의견을 제시하며, 이는 수치나
[B0015-s004] False (hcx) 현재 문장은 특정 행사의 참석자 범위 및 방식에 대한 설명으로, 수치나
[B0016-s000] False (hcx) 문장은 특정 사건에 대한 법적 조치에 관한 내용으로, 수치나 통계적 변화
[B0016-s001] False (hcx) 특별법 제정에 대한 내용은 수치나 통계적인 변화를 주장하는 것이 아닙니다
[B0016-s002] False (hcx) 현재 문장은 특정 사건에 대한 특별법 제정과 관련된 내용으로, 수치나 통
[B0016-s003] False (hcx) 김영록 전남지사가 기자회견을 열었다는 사실은 단순한 사건 보고이므로 KO
[B0016-s004] False (hcx) 특별법 제정과 관련된 예산 및 시설 계획이므로 KOSIS 통계와는 관련이
[B0016-s005] False (hcx) 현재 문장은 추모탑과 유가족을 위한 시설 및 방문객 센터를 조성할 예정이
[B0016-s006] False (hcx) 현재 문장은 최첨단 조류 감시 및 퇴치 시스템 도입과 대형 항공기 이착륙
[B0016-s007] False (hcx) 문장에서 주장하는 내용은 희생자를 추모하기 위한 행사에 관한 것이며, 이
[B0016-s008] False (hcx) 현재 문장은 특정 사건에 대한 정부의 대응 및 행사에 관한 내용으로, 수
[B0016-s009] False (hcx) 참석자 수는 단순한 사건 관련 정보로, KOSIS에서 제공하는 통계와는
[B0016-s010] False (hcx) 무안공항의 재개장 시기에 대한 정보는 특정한 수치나 통계적 변화를 주장하
[B0016-s011] False (hcx) 문장은 무안공항의 폐쇄 기간에 대한 정보를 제공하고 있으며, 이는 특정한
[B0016-s012] False (hcx) 문장은 무안공항의 폐쇄 기간 연장에 대한 사실을 전달하지만, 이는 특정한
[B0016-s013] False (hcx) 사고 현장인 활주로를 보존해야 한다는 내용은 특정 사건에 대한 설명이지,
[B0016-s014] False (hcx) 현재 문장은 참사 당시 파손된 착륙 유도 시설 등의 복구 기간에 대한 정
[B0016-s015] True (hcx) 사고 후 8일간 활동한 자원봉사자의 수가 5509명으로 집계되었다는 구체
[B0016-s016] False (hcx) 현재 문장은 특정 사건에서의 자원봉사자 수를 언급하며 이는 개별 사건에
[B0016-s017] True (hcx) 현재 문장은 '작년 상반기 항공기 정비를 이유로 지연 운항한 항공편이 가
[B0016-s018] True (hcx) 현재 문장은 제주항공이 작년 상반기에 운항한 항공편 중 몇 편이 항공기
[B0016-s019] True (hcx) 현재 문장은 제주항공의 지연 운항 편수에 대해 언급하며, 이를 다른 항공
[B0016-s020] False (hcx) 현재 문장은 제주항공의 운영 방식에 대한 지적이지, 구체적인 수치나 통계
[B0016-s021] True (hcx) 현재 문장은 제주항공 참사 이후 제주도를 찾은 관광객 수가 감소했다는 내
[B0016-s022] True (hcx) 현재 문장은 제주항공 참사 이후 일주일 동안 제주도를 방문한 관광객 수가
[B0016-s023] True (hcx) 현재 문장은 제주도를 방문한 내국인 관광객 수가 전년 대비 얼마나 감소했
[B0016-s024] True (hcx) 문장에서 '제주항공 참사 이후 제주항공 등 저비용항공사를 이용해 제주도를
[B0017-s000] False (hcx) 현재 문장은 특정 제품의 판매 순위에 대한 정보이므로 KOSIS 통계로
[B0017-s001] True (hcx) 내수 부진으로 수입차 판매가 줄어들었다는 내용은 국내 경제 상황에 대한
[B0017-s002] True (hcx) 현재 문장은 테슬라 모델 Y가 지난해 한국에서 몇 대 팔렸다는 구체적인
[B0017-s003] False (hcx) 현재 문장은 특정 차량 모델의 가격 할인과 그에 따른 소비자 반응에 대한
[B0017-s004] False (hcx) 현재 문장은 특정 자동차 모델들의 판매량 순위에 대한 정보이므로, 이는
[B0017-s005] False (hcx) 현재 문장은 특정 차량 모델들의 판매량에 대한 정보를 제공하고 있지만,
[B0017-s006] True (hcx) 현재 문장은 전체 수입차 판매량이 2023년에 비해 2.9% 감소했다는
[B0017-s007] True (hcx) 브랜드별 성장률을 언급하며 BMW와 메르세데스-벤츠의 판매량 변화를 수치
[B0017-s008] True (hcx) 현재 문장에서 테슬라의 판매량이 2023년의 두 배에 가깝다고 언급되어
[B0017-s009] True (hcx) 연료별 차량 판매 비율을 제시하고 있으며, 이는 국가통계포털(KOSIS)
[B0017-s010] True (hcx) 현재 문장은 하이브리드와 전기차 판매량이 증가한 것에 대한 구체적인 수치
[B0017-s011] True (hcx) 플러그인하이브리드와 디젤 차량의 비율이 변동되었다는 내용은 국내 자동차
[B0017-s012] False (hcx) 현재 문장은 단순한 정보 전달로서, 어떠한 수치나 비율 등의 변화를 주장
[B0018-s000] True (hcx) 현대차그룹이 지난해 미국 시장에서 170만대 이상 판매하여 2년 연속 역
[B0018-s001] True (hcx) 현대차그룹의 지난해 국내 내수 판매가 전년 대비 감소하고, 유럽과 중남미
[B0018-s002] True (hcx) 현대차그룹의 미국 시장 판매량 증가율을 구체적으로 제시하여, 이는 KOS
[B0018-s003] True (hcx) 현대차의 미국 시장 판매량 증가율 및 각 브랜드별 판매량을 언급하고 있어
[B0018-s004] False (hcx) 현재 문장은 현대차그룹 및 각 브랜드의 실적에 대한 설명을 하고 있지만,
[B0018-s005] True (hcx) 현대차의 미국 시장 판매량에 대한 구체적인 수치와 변화를 언급하고 있으며
[B0018-s006] False (hcx) 현대차의 아이오닉5, 팰리세이드, 기아의 스포티지, 카니발, EV6 등의
[B0019-s000] True (hcx) 문장에서 '지난해 여름 폭염 등의 영향으로 설 성수품인 배추, 무 등의
[B0019-s001] True (hcx) 현재 문장은 배추의 평균 소매가격이 1년 전 및 평년에 비해 얼마나 올랐
[B0019-s002] False (hcx) 현재 문장은 평년 가격에 대한 정의를 설명하고 있으며, 이는 특정한 수치
[B0019-s003] True (hcx) 현재 문장은 무의 가격이 작년 대비 얼마나 상승했는지 구체적인 비율을 제
[B0019-s004] False (hcx) 현재 문장은 배추와 무의 가격 상승 원인을 설명하며, 이는 단순한 원인
[B0019-s005] False (hcx) 현재 문장은 기후 변화에 따른 농산물 생육 부진에 대한 설명을 하고 있으
[B0019-s006] False (hcx) 현재 문장은 배추와 무의 조기 출하에 대한 설명을 하고 있으며, 이는 특
[B0019-s007] False (hcx) 현재 문장은 정부의 정책 대응에 대한 내용으로, 특정한 수치나 통계적 변
[B0019-s008] False (hcx) 현재 문장은 정부의 대책 및 계획에 대한 내용으로, 특정한 수치나 통계적
[B0020-s000] True (hcx) 문장에서 한국과 중국 간의 수출액 차이가 21년 만에 최소치를 기록했다고
[B0020-s001] False (hcx) 현재 문장은 한중간 교역의 위축 원인에 대한 설명을 하고 있으며, 구체적
[B0020-s002] True (hcx) 현재 문장은 한국과 미국의 교역 및 투자 상황에 대한 변화를 언급하며,
[B0020-s003] True (hcx) 현재 문장은 지난해 대중 수출액이 전년 대비 증가한 수치적인 정보를 제공
[B0020-s004] True (hcx) 현재 문장은 대미 수출액이 1년 전에 비해 얼마나 증가했는지를 수치로 제
[B0020-s005] True (hcx) 현재 문장은 한국과 중국 간의 수출액과 한국과 미국 간의 수출액을 비교하
[B0020-s006] True (hcx) 현재 문장은 한국과 중국 간의 수출액과 한국과 미국 간의 수출액 사이의
[B0020-s007] True (hcx) 현재 문장은 한국과 중국 및 미국 간의 수출액 차이를 언급하며, 이는 국
[B0020-s008] True (hcx) 현재 문장은 대미 수출액이 매년 역대 최대치를 갱신하며 2022년에 처음
[B0020-s009] True (hcx) 현재 문장은 반도체와 자동차 등의 주요 품목들이 대미 수출에서 활기를 띠
[B0020-s010] True (hcx) 현재 문장은 대중 수출액의 변화에 대한 구체적인 수치를 포함하고 있으며,
[B0020-s011] False (hcx) 현재 문장은 중국의 내수 부진과 자체적인 중간재 조달 상황에 대한 설명을
[B0020-s012] False (hcx) 현재 문장은 한국과 중국의 전통적인 공급망 구조에 대한 설명으로, 특정한
[B0020-s013] False (hcx) 현재 문장은 미국의 수출 대상국 1위 자리 가능성에 대한 예측 및 분석을
[B0020-s014] False (hcx) 현재 문장은 미국의 새로운 정책이 한국에 미칠 영향에 대한 예측이므로,
[B0020-s015] False (hcx) 현재 문장은 단순한 예측이나 추측으로서 구체적인 수치나 통계적 변화를 언
[B0021-s000] False (hcx) 문장은 특정 기업의 활동 및 계획에 대한 내용으로, 수치나 통계적인 변화
[B0021-s001] False (hcx) 현재 문장은 특정 기업의 활동 및 계획에 대한 내용으로, 수치나 통계적인
[B0021-s002] False (hcx) 문장은 단순히 이벤트 일정 및 참여 정보를 전달하며, 수치나 통계적 변화
[B0021-s003] False (hcx) 현재 문장은 특정 기업의 전시회 참여 및 주제 관련 내용으로, 수치나 통
[B0021-s004] False (hcx) 현재 문장은 AI 기술의 상용화와 관련된 계획 및 전략에 대한 내용으로,
[B0021-s005] False (hcx) 현재 문장은 SK그룹이 CES 2025에서 AI 기술을 통해 일상에 변화
[B0021-s006] False (hcx) 현재 문장은 최태원 회장의 발언 내용으로, 이는 단순한 의견 표명 및 목
[B0021-s007] False (hcx) 현재 문장은 SK그룹의 CES 전시 구성에 대한 설명으로, 수치나 통계적
[B0021-s008] False (hcx) 현재 문장은 SK가 보유한 AI 기술이 미래에 미칠 영향에 대한 단순한

In [ ]:
!python filter_true_claims.py --input is_claim_result.csv --output claims_filtered.csv

생성: claims_filtered.csv
전체 문장: 840 | is_claim=True: 206 (25%) | 그중 confidence=low: 1 | 숫자 없는 True(추세 주장): 39

In [ ]:
!python extract_hcx.py --input claims_filtered.csv --output hcx_extracted.csv

[B0001-s001] ok (3 행, repair=N, fallback=0, binding=0, period_removed=0)
[B0001-s007] ok (1 행, repair=N, fallback=0, binding=0, period_removed=0)
[B0001-s008] ok (2 행, repair=N, fallback=0, binding=0, period_removed=0)
[B0001-s009] ok (2 행, repair=N, fallback=0, binding=0, period_removed=0)
[B0001-s010] ok (2 행, repair=N, fallback=0, binding=0, period_removed=0)
[B0001-s020] ok (1 행, repair=N, fallback=0, binding=0, period_removed=0)
[B0001-s031] ok (1 행, repair=N, fallback=0, binding=0, period_removed=0)
[B0001-s046] ok (1 행, repair=N, fallback=0, binding=0, period_removed=0)
[B0002-s008] ok (1 행, repair=N, fallback=0, binding=0, period_removed=0)
[B0004-s001] ok (2 행, repair=N, fallback=0, binding=0, period_removed=0)
[B0004-s002] ok (4 행, repair=Y, fallback=1, binding=0, period_removed=1)
[B0004-s003] ok (4 행, repair=N, fallback=0, binding=0, period_removed=0)
[B0004-s004] ok (4 행, repair=N, fallback=0, binding=0, period_removed=0)
[B0004-s005] ok (1 행, repair=N, fallback=0, binding=0, period_removed=0)
[B0004-s007] ok (4 행, repair=N, fallback=0, binding=0, period_removed=0)
[B0004-s008] ok (7 행, repair=Y, fallback=0, binding=0, period_removed=0)
[B0004-s009] ok (4 행, repair=N, fallback=0, binding=0, period_removed=0)
[B0006-s001] ok (1 행, repair=Y, fallback=0, binding=0, period_removed=0)
[B0006-s002] ok (4 행, repair=N, fallback=0, binding=0, period_removed=0)
[B0006-s003] ok (1 행, repair=N, fallback=0, binding=0, period_removed=0)
[B0006-s005] ok (2 행, repair=N, fallback=0, binding=0, period_removed=0)
[B0006-s011] ok (2 행, repair=N, fallback=0, binding=0, period_removed=0)
[B0006-s015] ok (1 행, repair=N, fallback=0, binding=0, period_removed=0)
[B0006-s016] ok (1 행, repair=N, fallback=0, binding=0, period_removed=0)
[B0006-s017] ok (1 행, repair=N, fallback=0, binding=0, period_removed=0)
[B0006-s018] ok (1 행, repair=N, fallback=0, binding=0, period_removed=0)
[B0006-s019] ok (1 행, repair=N, fallback=0, binding=0, period_removed=0)
[B0006-s021] ok (3 행, repair=Y, fallback=0, binding=0, period_removed=0)
[B0007-s005] ok (1 행, repair=N, fallback=0, binding=0, period_removed=0)
[B0007-s006] ok (2 행, repair=Y, fallback=0, binding=0, period_removed=0)
[B0009-s008] ok (2 행, repair=Y, fallback=0, binding=1, period_removed=2)
[B0011-s000] ok (2 행, repair=N, fallback=0, binding=1, period_removed=1)
[B0011-s002] ok (2 행, repair=Y, fallback=0, binding=0, period_removed=0)
[B0011-s003] ok (4 행, repair=Y, fallback=0, binding=2, period_removed=0)
[B0011-s005] ok (1 행, repair=N, fallback=0, binding=0, period_removed=0)
[B0011-s006] ok (2 행, repair=N, fallback=0, binding=1, period_removed=2)
[B0011-s007] ok (5 행, repair=Y, fallback=2, binding=0, period_removed=0)
[B0011-s009] ok (1 행, repair=N, fallback=0, binding=0, period_removed=0)
[B0013-s019] ok (2 행, repair=N, fallback=0, binding=0, period_removed=1)
[B0014-s001] ok (2 행, repair=N, fallback=0, binding=0, period_removed=0)
[B0014-s002] ok (1 행, repair=N, fallback=0, binding=0, period_removed=0)
[B0014-s005] ok (2 행, repair=N, fallback=0, binding=0, period_removed=0)
[B0016-s015] ok (1 행, repair=N, fallback=0, binding=0, period_removed=1)
[B0016-s017] ok (1 행, repair=N, fallback=0, binding=0, period_removed=0)
[B0016-s018] ok (2 행, repair=N, fallback=0, binding=0, period_removed=0)
[B0016-s019] ok (1 행, repair=N, fallback=0, binding=0, period_removed=0)
[B0016-s021] ok (1 행, repair=N, fallback=0, binding=0, period_removed=0)
[B0016-s022] ok (3 행, repair=N, fallback=0, binding=0, period_removed=3)
[B0016-s023] ok (2 행, repair=N, fallback=0, binding=0, period_removed=2)
[B0016-s024] ok (1 행, repair=N, fallback=0, binding=0, period_removed=0)
[B0017-s001] ok (1 행, repair=N, fallback=0, binding=0, period_removed=0)
[B0017-s002] ok (1 행, repair=N, fallback=0, binding=0, period_removed=0)
[B0017-s006] ok (3 행, repair=N, fallback=0, binding=0, period_removed=0)
[B0017-s007] ok (5 행, repair=Y, fallback=0, binding=0, period_removed=0)
[B0017-s008] ok (4 행, repair=Y, fallback=0, binding=0, period_removed=0)
[B0017-s009] ok (4 행, repair=N, fallback=0, binding=0, period_removed=0)
[B0017-s010] ok (3 행, repair=N, fallback=0, binding=0, period_removed=0)
[B0017-s011] ok (3 행, repair=N, fallback=0, binding=0, period_removed=0)
[B0018-s000] ok (2 행, repair=N, fallback=0, binding=1, period_removed=0)
[B0018-s001] ok (1 행, repair=N, fallback=0, binding=0, period_removed=0)
[B0018-s002] ok (3 행, repair=Y, fallback=0, binding=1, period_removed=1)
[B0018-s003] ok (6 행, repair=N, fallback=0, binding=0, period_removed=0)
[B0018-s005] ok (1 행, repair=N, fallback=0, binding=0, period_removed=0)
[B0019-s000] ok (2 행, repair=N, fallback=0, binding=0, period_removed=0)
[B0019-s001] ok (4 행, repair=Y, fallback=1, binding=0, period_removed=3)
[B0019-s003] ok (4 행, repair=Y, fallback=1, binding=0, period_removed=3)
[B0020-s000] ok (1 행, repair=N, fallback=0, binding=0, period_removed=0)
[B0020-s002] ok (1 행, repair=N, fallback=0, binding=0, period_removed=0)
[B0020-s003] ok (2 행, repair=N, fallback=0, binding=0, period_removed=0)
[B0020-s004] ok (3 행, repair=Y, fallback=0, binding=0, period_removed=0)
[B0020-s005] ok (1 행, repair=N, fallback=0, binding=0, period_removed=0)
[B0020-s006] ok (2 행, repair=N, fallback=0, binding=0, period_removed=0)
[B0020-s007] ok (2 행, repair=N, fallback=0, binding=1, period_removed=1)
[B0020-s008] ok (2 행, repair=N, fallback=0, binding=0, period_removed=0)
[B0020-s009] ok (2 행, repair=N, fallback=0, binding=0, period_removed=0)
[B0020-s010] ok (3 행, repair=N, fallback=0, binding=0, period_removed=0)
[B0022-s002] ok (1 행, repair=N, fallback=0, binding=0, period_removed=0)
[B0022-s003] ok (2 행, repair=Y, fallback=0, binding=0, period_removed=0)
[B0022-s004] ok (1 행, repair=N, fallback=0, binding=0, period_removed=0)
[B0022-s008] ok (3 행, repair=N, fallback=0, binding=0, period_removed=0)
[B0022-s010] ok (2 행, repair=Y, fallback=0, binding=2, period_removed=0)
[B0022-s020] ok (1 행, repair=N, fallback=0, binding=0, period_removed=0)
[B0022-s021] ok (1 행, repair=N, fallback=0, binding=0, period_removed=0)
[B0022-s022] ok (5 행, repair=Y, fallback=0, binding=1, period_removed=1)
[B0022-s023] ok (1 행, repair=N, fallback=0, binding=0, period_removed=0)
[B0022-s024] ok (4 행, repair=Y, fallback=1, binding=0, period_removed=0)
[B0022-s026] ok (1 행, repair=N, fallback=0, binding=0, period_removed=0)
[B0022-s027] ok (1 행, repair=N, fallback=0, binding=0, period_removed=0)
[B0022-s028] ok (1 행, repair=N, fallback=0, binding=0, period_removed=0)
[B0022-s029] ok (2 행, repair=Y, fallback=0, binding=1, period_removed=2)
[B0022-s030] ok (4 행, repair=Y, fallback=0, binding=1, period_removed=4)
[B0022-s031] ok (1 행, repair=Y, fallback=0, binding=0, period_removed=0)
[B0022-s032] ok (1 행, repair=Y, fallback=0, binding=0, period_removed=1)
[B0022-s033] ok (1 행, repair=Y, fallback=0, binding=0, period_removed=0)
[B0022-s035] ok (3 행, repair=Y, fallback=0, binding=1, period_removed=3)
[B0022-s039] ok (1 행, repair=Y, fallback=0, binding=0, period_removed=0)
[B0022-s040] ok (4 행, repair=Y, fallback=1, binding=0, period_removed=0)
[B0023-s000] ok (1 행, repair=N, fallback=0, binding=0, period_removed=0)
[B0023-s001] ok (1 행, repair=N, fallback=0, binding=0, period_removed=0)
[B0023-s002] ok (2 행, repair=N, fallback=0, binding=0, period_removed=0)
[B0023-s003] ok (2 행, repair=Y, fallback=0, binding=0, period_removed=0)
[B0023-s005] ok (1 행, repair=N, fallback=0, binding=0, period_removed=0)
[B0023-s006] ok (1 행, repair=N, fallback=0, binding=0, period_removed=0)
[B0023-s007] ok (1 행, repair=N, fallback=0, binding=0, period_removed=0)
[B0023-s011] ok (1 행, repair=N, fallback=0, binding=0, period_removed=0)
[B0023-s012] ok (2 행, repair=N, fallback=0, binding=0, period_removed=0)
[B0023-s013] ok (2 행, repair=N, fallback=0, binding=0, period_removed=0)
[B0023-s014] ok (2 행, repair=N, fallback=0, binding=0, period_removed=2)
[B0025-s002] ok (4 행, repair=Y, fallback=0, binding=0, period_removed=0)
[B0025-s003] ok (1 행, repair=N, fallback=0, binding=0, period_removed=0)
[B0025-s004] ok (5 행, repair=N, fallback=0, binding=0, period_removed=0)
[B0025-s006] ok (3 행, repair=N, fallback=0, binding=0, period_removed=0)
[B0025-s007] ok (10 행, repair=Y, fallback=0, binding=0, period_removed=0)
[B0025-s008] ok (4 행, repair=Y, fallback=0, binding=0, period_removed=0)
[B0025-s009] ok (1 행, repair=N, fallback=0, binding=0, period_removed=0)
[B0025-s010] ok (3 행, repair=N, fallback=0, binding=0, period_removed=0)
[B0025-s011] ok (3 행, repair=N, fallback=0, binding=0, period_removed=0)
[B0025-s012] ok (4 행, repair=Y, fallback=0, binding=0, period_removed=0)
[B0026-s000] ok (1 행, repair=N, fallback=0, binding=0, period_removed=1)
[B0026-s001] ok (1 행, repair=N, fallback=0, binding=0, period_removed=0)
[B0026-s003] ok (1 행, repair=N, fallback=0, binding=0, period_removed=0)
[B0026-s004] ok (3 행, repair=N, fallback=0, binding=0, period_removed=0)
[B0026-s005] ok (4 행, repair=Y, fallback=0, binding=1, period_removed=0)
[B0026-s007] ok (3 행, repair=N, fallback=0, binding=0, period_removed=0)
[B0026-s008] ok (3 행, repair=N, fallback=0, binding=0, period_removed=0)
[B0026-s011] ok (2 행, repair=N, fallback=0, binding=0, period_removed=0)
[B0026-s013] ok (1 행, repair=N, fallback=0, binding=0, period_removed=0)
[B0026-s014] ok (1 행, repair=N, fallback=0, binding=0, period_removed=0)
[B0027-s001] ok (5 행, repair=Y, fallback=0, binding=0, period_removed=2)
[B0027-s002] ok (2 행, repair=N, fallback=0, binding=0, period_removed=1)
[B0027-s005] ok (3 행, repair=Y, fallback=0, binding=0, period_removed=0)
[B0027-s007] ok (4 행, repair=N, fallback=0, binding=0, period_removed=0)
[B0027-s012] ok (2 행, repair=N, fallback=0, binding=0, period_removed=0)
[B0027-s013] ok (1 행, repair=N, fallback=0, binding=0, period_removed=0)
[B0027-s015] ok (2 행, repair=Y, fallback=0, binding=0, period_removed=0)
[B0027-s016] ok (2 행, repair=N, fallback=0, binding=0, period_removed=0)
[B0027-s017] ok (1 행, repair=Y, fallback=0, binding=0, period_removed=0)
[B0027-s018] ok (1 행, repair=Y, fallback=1, binding=0, period_removed=0)
[B0027-s019] ok (4 행, repair=Y, fallback=0, binding=0, period_removed=0)
[B0027-s020] ok (5 행, repair=Y, fallback=0, binding=0, period_removed=0)
[B0028-s005] ok (1 행, repair=N, fallback=0, binding=0, period_removed=0)
[B0031-s003] ok (1 행, repair=N, fallback=0, binding=0, period_removed=0)
[B0031-s006] ok (3 행, repair=Y, fallback=0, binding=0, period_removed=0)
[B0031-s007] ok (7 행, repair=N, fallback=0, binding=0, period_removed=0)
[B0032-s009] ok (1 행, repair=N, fallback=0, binding=0, period_removed=0)
[B0033-s007] ok (1 행, repair=N, fallback=0, binding=0, period_removed=0)
[B0034-s000] ok (1 행, repair=Y, fallback=0, binding=0, period_removed=0)
[B0034-s001] ok (1 행, repair=N, fallback=0, binding=0, period_removed=0)
[B0034-s002] ok (2 행, repair=N, fallback=0, binding=0, period_removed=0)
[B0034-s003] ok (2 행, repair=N, fallback=0, binding=0, period_removed=0)
[B0034-s004] ok (1 행, repair=N, fallback=0, binding=0, period_removed=0)
[B0034-s005] ok (1 행, repair=N, fallback=0, binding=0, period_removed=0)
[B0034-s007] ok (1 행, repair=N, fallback=0, binding=0, period_removed=0)
[B0034-s008] ok (1 행, repair=N, fallback=0, binding=0, period_removed=0)
[B0034-s009] ok (4 행, repair=Y, fallback=0, binding=0, period_removed=0)
[B0034-s010] ok (2 행, repair=N, fallback=0, binding=0, period_removed=0)
[B0035-s001] ok (1 행, repair=N, fallback=0, binding=0, period_removed=0)
[B0035-s019] ok (1 행, repair=N, fallback=0, binding=0, period_removed=0)
[B0035-s030] ok (3 행, repair=N, fallback=0, binding=0, period_removed=1)
[B0035-s032] ok (1 행, repair=N, fallback=0, binding=0, period_removed=0)
[B0035-s033] ok (1 행, repair=N, fallback=0, binding=0, period_removed=0)
[B0035-s035] ok (1 행, repair=N, fallback=0, binding=0, period_removed=0)
[B0035-s043] ok (1 행, repair=N, fallback=0, binding=0, period_removed=0)
[B0035-s044] ok (1 행, repair=N, fallback=0, binding=0, period_removed=0)
[B0036-s001] ok (1 행, repair=N, fallback=0, binding=0, period_removed=0)
[B0036-s003] ok (2 행, repair=Y, fallback=0, binding=0, period_removed=0)
[B0036-s007] ok (3 행, repair=N, fallback=0, binding=0, period_removed=0)
[B0036-s009] ok (2 행, repair=Y, fallback=0, binding=0, period_removed=0)
[B0036-s012] ok (1 행, repair=N, fallback=0, binding=0, period_removed=0)
[B0039-s009] ok (1 행, repair=Y, fallback=0, binding=1, period_removed=1)
[B0041-s000] ok (1 행, repair=N, fallback=0, binding=1, period_removed=0)
[B0041-s001] ok (1 행, repair=N, fallback=0, binding=0, period_removed=0)
[B0041-s002] ok (1 행, repair=Y, fallback=0, binding=0, period_removed=0)
[B0041-s003] ok (2 행, repair=Y, fallback=0, binding=1, period_removed=0)
[B0041-s004] ok (1 행, repair=N, fallback=0, binding=0, period_removed=0)
[B0041-s005] ok (1 행, repair=N, fallback=0, binding=0, period_removed=0)
[B0041-s006] ok (2 행, repair=N, fallback=0, binding=0, period_removed=0)
[B0041-s008] ok (1 행, repair=N, fallback=0, binding=0, period_removed=0)
[B0041-s014] ok (1 행, repair=N, fallback=0, binding=0, period_removed=1)
[B0046-s000] ok (1 행, repair=N, fallback=0, binding=0, period_removed=0)
[B0046-s001] ok (1 행, repair=N, fallback=0, binding=0, period_removed=0)
[B0046-s002] ok (2 행, repair=N, fallback=0, binding=0, period_removed=0)
[B0046-s004] ok (1 행, repair=N, fallback=0, binding=0, period_removed=0)
[B0046-s005] ok (1 행, repair=N, fallback=0, binding=0, period_removed=0)
[B0046-s007] ok (1 행, repair=N, fallback=0, binding=0, period_removed=0)
[B0046-s008] ok (1 행, repair=N, fallback=0, binding=0, period_removed=0)
[B0046-s009] ok (3 행, repair=N, fallback=0, binding=0, period_removed=0)
[B0047-s009] ok (3 행, repair=N, fallback=0, binding=0, period_removed=0)
[B0047-s011] ok (5 행, repair=N, fallback=0, binding=0, period_removed=0)
[B0047-s013] ok (6 행, repair=Y, fallback=1, binding=0, period_removed=0)
[B0048-s001] ok (2 행, repair=N, fallback=0, binding=1, period_removed=2)
[B0048-s014] ok (1 행, repair=Y, fallback=0, binding=0, period_removed=0)
[B0048-s020] ok (2 행, repair=N, fallback=0, binding=0, period_removed=0)
[B0048-s024] ok (1 행, repair=N, fallback=0, binding=0, period_removed=1)
[B0048-s027] ok (2 행, repair=Y, fallback=0, binding=0, period_removed=2)
[B0048-s028] ok (1 행, repair=N, fallback=0, binding=0, period_removed=1)
[B0048-s030] ok (1 행, repair=N, fallback=0, binding=0, period_removed=1)
[B0050-s004] ok (1 행, repair=N, fallback=0, binding=0, period_removed=0)
[B0050-s005] ok (1 행, repair=N, fallback=0, binding=0, period_removed=0)
[B0050-s006] ok (1 행, repair=N, fallback=0, binding=0, period_removed=1)
[B0050-s017] ok (1 행, repair=N, fallback=0, binding=0, period_removed=0)
[B0050-s019] ok (1 행, repair=Y, fallback=0, binding=0, period_removed=0)
[B0050-s020] ok (1 행, repair=Y, fallback=0, binding=0, period_removed=0)
[B0050-s024] ok (1 행, repair=N, fallback=0, binding=0, period_removed=0)
[B0050-s032] ok (1 행, repair=N, fallback=0, binding=0, period_removed=0)
[B0050-s033] ok (1 행, repair=N, fallback=0, binding=0, period_removed=0)
완료 → hcx_extracted.csv

## 1. 스크립트 & 데이터 업로드

파일 선택 창에서 `extract_hcx.py`, `extract_article_claims_hcx.py`, 기사 원문 CSV를
한 번에 선택해서 업로드하세요.

In [ ]:
from google.colab import files

uploaded = files.upload()
print("업로드됨:", list(uploaded.keys()))

업로드됨: []

### (대안) Google Drive에 스크립트를 미리 저장해두셨다면

In [ ]:
# from google.colab import drive
# drive.mount('/content/drive')
#
# import shutil, os
# SRC_DIR = '/content/drive/MyDrive/여기에_실제_폴더_경로'
# for fname in ['extract_hcx.py', 'extract_article_claims_hcx.py']:
#     shutil.copy(os.path.join(SRC_DIR, fname), fname)
# print('스크립트 복사 완료')

## 2. CLOVA_API_KEY 로드 (Colab 보안 비밀)

In [ ]:
import os
from google.colab import userdata

key = userdata.get('CLOVA_API_KEY')
os.environ['CLOVA_API_KEY'] = key or ''
print('키 로드 완료 (길이 {}자)'.format(len(key)) if key else
      '키를 찾을 수 없습니다 - 보안 비밀 이름()과 "노트북 액세스" 토글을 확인하세요')

키 로드 완료 (길이 39자)

In [4]:
import os
from google.colab import userdata
os.environ["CLOVA_API_KEY"] = userdata.get("CLOVA_API_KEY")
os.environ["KOSIS_API_KEY"] = userdata.get("KOSIS_API_KEY")
print("CLOVA:", bool(os.environ.get("CLOVA_API_KEY")), "| KOSIS:", bool(os.environ.get("KOSIS_API_KEY")))

CLOVA: True | KOSIS: True

In [ ]:
# 1) 놓친 도메인만 같은 파일에 이어붙이기
!python crawl_kosis_catalog.py --output kosis_full_catalog.csv \
    --top-category-keywords "도소매ㆍ서비스,소득ㆍ소비ㆍ자산" --resume --max-tables 5000
!python crawl_kosis_catalog.py --output kosis_full_catalog.csv \
    --top-category-keywords "물가,인구,정부ㆍ재정,임금,보건,복지" --resume --max-tables 5000

kosis_full_catalog.csv 가 이미 있습니다 - 기존 70개 표는 건너뛰고 이어서 append 합니다.
(카테고리 트리는 처음부터 다시 훑지만, 이미 모은 표는 중복으로 다시 안 씁니다.)
크롤링 시작: vw_cd=MT_ZTITLE, max_depth=무제한, top_category_keywords=['도소매ㆍ서비스', '소득ㆍ소비ㆍ자산'], max_tables=5000
진행: 카테고리 호출 20개 완료, 지금까지 표 266개, 대기 중인 카테고리 29개
실패 (parent_id='113_11308_011', path=도소매ㆍ서비스/콘텐츠산업조사/지식정보산업): ConnectionError: HTTPSConnectionPool(host='kosis.kr', port=443): Max retries exceeded with url: /openapi/statisticsList.do?method=getList&apiKey=ZTFiMTMzZDliNDQyYmRlMWI5MjJjMmUxNzgyODg3NGM%3D&vwCd=MT_ZTITLE&parentListId=113_11308_011&format=json (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7d965f414770>: Failed to resolve 'kosis.kr' ([Errno -5] No address associated with hostname)"))
실패 (parent_id='113_11308_010', path=도소매ㆍ서비스/콘텐츠산업조사/캐릭터사업): ConnectionError: HTTPSConnectionPool(host='kosis.kr', port=443): Max retries exceeded with url: /openapi/statisticsList.do?method=getList&apiKey=ZTFiMTMzZDliNDQyYmRlMWI5MjJjMmUxNzgyODg3NGM%3D&vwCd=MT_ZTITLE&parentListId=113_11308_010&format=json (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7d965f416a80>: Failed to resolve 'kosis.kr' ([Errno -5] No address associated with hostname)"))
실패 (parent_id='113_11308_009', path=도소매ㆍ서비스/콘텐츠산업조사/광고산업): ConnectionError: HTTPSConnectionPool(host='kosis.kr', port=443): Max retries exceeded with url: /openapi/statisticsList.do?method=getList&apiKey=ZTFiMTMzZDliNDQyYmRlMWI5MjJjMmUxNzgyODg3NGM%3D&vwCd=MT_ZTITLE&parentListId=113_11308_009&format=json (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7d965f415190>: Failed to resolve 'kosis.kr' ([Errno -5] No address associated with hostname)"))
실패 (parent_id='113_11308_008', path=도소매ㆍ서비스/콘텐츠산업조사/방송산업): ConnectionError: HTTPSConnectionPool(host='kosis.kr', port=443): Max retries exceeded with url: /openapi/statisticsList.do?method=getList&apiKey=ZTFiMTMzZDliNDQyYmRlMWI5MjJjMmUxNzgyODg3NGM%3D&vwCd=MT_ZTITLE&parentListId=113_11308_008&format=json (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7d965f417440>: Failed to resolve 'kosis.kr' ([Errno -3] Temporary failure in name resolution)"))
진행: 카테고리 호출 40개 완료, 지금까지 표 606개, 대기 중인 카테고리 18개
진행: 카테고리 호출 60개 완료, 지금까지 표 753개, 대기 중인 카테고리 15개
진행: 카테고리 호출 80개 완료, 지금까지 표 997개, 대기 중인 카테고리 12개
진행: 카테고리 호출 100개 완료, 지금까지 표 1262개, 대기 중인 카테고리 8개
실패 (parent_id='115_11526_021_001', path=도소매ㆍ서비스/디자인산업통계/2008년 이전/지방자치단체 현황/지자체 직원대상 디자인 교육): ConnectionError: HTTPSConnectionPool(host='kosis.kr', port=443): Max retries exceeded with url: /openapi/statisticsList.do?method=getList&apiKey=ZTFiMTMzZDliNDQyYmRlMWI5MjJjMmUxNzgyODg3NGM%3D&vwCd=MT_ZTITLE&parentListId=115_11526_021_001&format=json (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7d965f469070>: Failed to resolve 'kosis.kr' ([Errno -5] No address associated with hostname)"))
진행: 카테고리 호출 120개 완료, 지금까지 표 1498개, 대기 중인 카테고리 28개
진행: 카테고리 호출 140개 완료, 지금까지 표 1883개, 대기 중인 카테고리 21개
진행: 카테고리 호출 160개 완료, 지금까지 표 2150개, 대기 중인 카테고리 12개
진행: 카테고리 호출 180개 완료, 지금까지 표 2972개, 대기 중인 카테고리 9개
진행: 카테고리 호출 200개 완료, 지금까지 표 3227개, 대기 중인 카테고리 10개
실패 (parent_id='O_3_002', path=도소매ㆍ서비스/광고산업조사/2022년이후): ConnectionError: HTTPSConnectionPool(host='kosis.kr', port=443): Max retries exceeded with url: /openapi/statisticsList.do?method=getList&apiKey=ZTFiMTMzZDliNDQyYmRlMWI5MjJjMmUxNzgyODg3NGM%3D&vwCd=MT_ZTITLE&parentListId=O_3_002&format=json (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7d965f2b8f80>: Failed to resolve 'kosis.kr' ([Errno -5] No address associated with hostname)"))
진행: 카테고리 호출 220개 완료, 지금까지 표 4527개, 대기 중인 카테고리 2개
표 5000개 상한에 도달해서 멈춥니다.

완료: 표 5002개 발견, 카테고리 노드 242개, API 호출 237회, 키워드로 건너뛴 대분류 28개
저장: kosis_full_catalog.csv
kosis_full_catalog.csv 가 이미 있습니다 - 기존 5072개 표는 건너뛰고 이어서 append 합니다.
(카테고리 트리는 처음부터 다시 훑지만, 이미 모은 표는 중복으로 다시 안 씁니다.)
크롤링 시작: vw_cd=MT_ZTITLE, max_depth=무제한, top_category_keywords=['물가', '인구', '정부ㆍ재정', '임금', '보건', '복지'], max_tables=5000
진행: 카테고리 호출 20개 완료, 지금까지 표 100개, 대기 중인 카테고리 53개
진행: 카테고리 호출 40개 완료, 지금까지 표 198개, 대기 중인 카테고리 33개
진행: 카테고리 호출 60개 완료, 지금까지 표 290개, 대기 중인 카테고리 37개
진행: 카테고리 호출 80개 완료, 지금까지 표 375개, 대기 중인 카테고리 33개
실패 (parent_id='110_11006_014_037', path=정부ㆍ재정/지방세외수입징수실적/지방세외 징수실적(~1994)/세외수입 주요항목별 실적분석(전라남도)): ConnectionError: HTTPSConnectionPool(host='kosis.kr', port=443): Max retries exceeded with url: /openapi/statisticsList.do?method=getList&apiKey=ZTFiMTMzZDliNDQyYmRlMWI5MjJjMmUxNzgyODg3NGM%3D&vwCd=MT_ZTITLE&parentListId=110_11006_014_037&format=json (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7da5c8edf9b0>: Failed to resolve 'kosis.kr' ([Errno -5] No address associated with hostname)"))
진행: 카테고리 호출 100개 완료, 지금까지 표 498개, 대기 중인 카테고리 29개
진행: 카테고리 호출 120개 완료, 지금까지 표 547개, 대기 중인 카테고리 48개
진행: 카테고리 호출 140개 완료, 지금까지 표 611개, 대기 중인 카테고리 43개
실패 (parent_id='110_11006_016_033_005', path=정부ㆍ재정/지방세외수입징수실적/지방세외 징수실적(~1996)/세외수입 주요항목별 실적분석(대전광역시)/입장료): ConnectionError: HTTPSConnectionPool(host='kosis.kr', port=443): Max retries exceeded with url: /openapi/statisticsList.do?method=getList&apiKey=ZTFiMTMzZDliNDQyYmRlMWI5MjJjMmUxNzgyODg3NGM%3D&vwCd=MT_ZTITLE&parentListId=110_11006_016_033_005&format=json (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7da5c8ef2ae0>: Failed to resolve 'kosis.kr' ([Errno -5] No address associated with hostname)"))
진행: 카테고리 호출 180개 완료, 지금까지 표 728개, 대기 중인 카테고리 35개
진행: 카테고리 호출 200개 완료, 지금까지 표 840개, 대기 중인 카테고리 26개
진행: 카테고리 호출 220개 완료, 지금까지 표 1049개, 대기 중인 카테고리 22개
실패 (parent_id='110_11006_001_006_004', path=정부ㆍ재정/지방세외수입징수실적/세외수입 징수실적(2005~)/군/임시적 세외수입 징수실적): ConnectionError: HTTPSConnectionPool(host='kosis.kr', port=443): Max retries exceeded with url: /openapi/statisticsList.do?method=getList&apiKey=ZTFiMTMzZDliNDQyYmRlMWI5MjJjMmUxNzgyODg3NGM%3D&vwCd=MT_ZTITLE&parentListId=110_11006_001_006_004&format=json (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7da5c8ef8230>: Failed to resolve 'kosis.kr' ([Errno -5] No address associated with hostname)"))
진행: 카테고리 호출 240개 완료, 지금까지 표 1103개, 대기 중인 카테고리 18개
실패 (parent_id='D3_002_011', path=정부ㆍ재정/국가보훈대상자생활실태조사/노후보장): ConnectionError: HTTPSConnectionPool(host='kosis.kr', port=443): Max retries exceeded with url: /openapi/statisticsList.do?method=getList&apiKey=ZTFiMTMzZDliNDQyYmRlMWI5MjJjMmUxNzgyODg3NGM%3D&vwCd=MT_ZTITLE&parentListId=D3_002_011&format=json (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7da5c8ef9b20>: Failed to resolve 'kosis.kr' ([Errno -5] No address associated with hostname)"))
진행: 카테고리 호출 260개 완료, 지금까지 표 1233개, 대기 중인 카테고리 19개
진행: 카테고리 호출 280개 완료, 지금까지 표 1352개, 대기 중인 카테고리 20개
진행: 카테고리 호출 300개 완료, 지금까지 표 1492개, 대기 중인 카테고리 16개
진행: 카테고리 호출 320개 완료, 지금까지 표 1556개, 대기 중인 카테고리 28개
진행: 카테고리 호출 340개 완료, 지금까지 표 1627개, 대기 중인 카테고리 8개
진행: 카테고리 호출 360개 완료, 지금까지 표 1729개, 대기 중인 카테고리 37개
실패 (parent_id='110_11007_009_075', path=정부ㆍ재정/지방세통계/과거년도의 지방세 세목별 징수실적/지방세 통계(~1970)/시도군세 징수상황): ConnectionError: HTTPSConnectionPool(host='kosis.kr', port=443): Max retries exceeded with url: /openapi/statisticsList.do?method=getList&apiKey=ZTFiMTMzZDliNDQyYmRlMWI5MjJjMmUxNzgyODg3NGM%3D&vwCd=MT_ZTITLE&parentListId=110_11007_009_075&format=json (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7da5c8f054f0>: Failed to resolve 'kosis.kr' ([Errno -5] No address associated with hostname)"))
진행: 카테고리 호출 380개 완료, 지금까지 표 1862개, 대기 중인 카테고리 37개
진행: 카테고리 호출 400개 완료, 지금까지 표 1961개, 대기 중인 카테고리 39개
진행: 카테고리 호출 420개 완료, 지금까지 표 2088개, 대기 중인 카테고리 30개
진행: 카테고리 호출 440개 완료, 지금까지 표 2198개, 대기 중인 카테고리 26개
진행: 카테고리 호출 460개 완료, 지금까지 표 2242개, 대기 중인 카테고리 34개
실패 (parent_id='110_11007_020_150', path=정부ㆍ재정/지방세통계/과거년도의 지방세 세목별 징수실적/지방세 통계(~1989)/토지과다보유세 부과실적): ConnectionError: HTTPSConnectionPool(host='kosis.kr', port=443): Max retries exceeded with url: /openapi/statisticsList.do?method=getList&apiKey=ZTFiMTMzZDliNDQyYmRlMWI5MjJjMmUxNzgyODg3NGM%3D&vwCd=MT_ZTITLE&parentListId=110_11007_020_150&format=json (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7da5c8f29460>: Failed to resolve 'kosis.kr' ([Errno -5] No address associated with hostname)"))
진행: 카테고리 호출 480개 완료, 지금까지 표 2336개, 대기 중인 카테고리 21개
실패 (parent_id='110_11007_022_049', path=정부ㆍ재정/지방세통계/과거년도의 지방세 세목별 징수실적/지방세 통계(~1991)/면허세-정기분 과세상황): ConnectionError: HTTPSConnectionPool(host='kosis.kr', port=443): Max retries exceeded with url: /openapi/statisticsList.do?method=getList&apiKey=ZTFiMTMzZDliNDQyYmRlMWI5MjJjMmUxNzgyODg3NGM%3D&vwCd=MT_ZTITLE&parentListId=110_11007_022_049&format=json (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7da5c8f2b110>: Failed to resolve 'kosis.kr' ([Errno -5] No address associated with hostname)"))
진행: 카테고리 호출 500개 완료, 지금까지 표 2465개, 대기 중인 카테고리 31개
실패 (parent_id='110_11007_025_052', path=정부ㆍ재정/지방세통계/과거년도의 지방세 세목별 징수실적/지방세 통계(~1994)/보통징수 과세상황): ConnectionError: HTTPSConnectionPool(host='kosis.kr', port=443): Max retries exceeded with url: /openapi/statisticsList.do?method=getList&apiKey=ZTFiMTMzZDliNDQyYmRlMWI5MjJjMmUxNzgyODg3NGM%3D&vwCd=MT_ZTITLE&parentListId=110_11007_025_052&format=json (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7da5c8cd7110>: Failed to resolve 'kosis.kr' ([Errno -5] No address associated with hostname)"))
실패 (parent_id='110_11007_026_154', path=정부ㆍ재정/지방세통계/과거년도의 지방세 세목별 징수실적/지방세 통계(~1995)/화물자동차 과세상황): ConnectionError: HTTPSConnectionPool(host='kosis.kr', port=443): Max retries exceeded with url: /openapi/statisticsList.do?method=getList&apiKey=ZTFiMTMzZDliNDQyYmRlMWI5MjJjMmUxNzgyODg3NGM%3D&vwCd=MT_ZTITLE&parentListId=110_11007_026_154&format=json (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7da5c8cd79b0>: Failed to resolve 'kosis.kr' ([Errno -5] No address associated with hostname)"))
실패 (parent_id='110_11007_026_001', path=정부ㆍ재정/지방세통계/과거년도의 지방세 세목별 징수실적/지방세 통계(~1995)/3륜이하 소형자동차과세상황): ConnectionError: HTTPSConnectionPool(host='kosis.kr', port=443): Max retries exceeded with url: /openapi/statisticsList.do?method=getList&apiKey=ZTFiMTMzZDliNDQyYmRlMWI5MjJjMmUxNzgyODg3NGM%3D&vwCd=MT_ZTITLE&parentListId=110_11007_026_001&format=json (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7da5c8cd7aa0>: Failed to resolve 'kosis.kr' ([Errno -5] No address associated with hostname)"))
실패 (parent_id='110_11007_027', path=정부ㆍ재정/지방세통계/과거년도의 지방세 세목별 징수실적/지방세 통계(~1996)): ConnectionError: HTTPSConnectionPool(host='kosis.kr', port=443): Max retries exceeded with url: /openapi/statisticsList.do?method=getList&apiKey=ZTFiMTMzZDliNDQyYmRlMWI5MjJjMmUxNzgyODg3NGM%3D&vwCd=MT_ZTITLE&parentListId=110_11007_027&format=json (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7da5c8f2b800>: Failed to resolve 'kosis.kr' ([Errno -5] No address associated with hostname)"))
진행: 카테고리 호출 540개 완료, 지금까지 표 2732개, 대기 중인 카테고리 19개
진행: 카테고리 호출 560개 완료, 지금까지 표 2881개, 대기 중인 카테고리 15개
진행: 카테고리 호출 580개 완료, 지금까지 표 2975개, 대기 중인 카테고리 20개
진행: 카테고리 호출 600개 완료, 지금까지 표 3050개, 대기 중인 카테고리 19개
진행: 카테고리 호출 620개 완료, 지금까지 표 3466개, 대기 중인 카테고리 17개
진행: 카테고리 호출 640개 완료, 지금까지 표 3827개, 대기 중인 카테고리 10개
실패 (parent_id='133_13301_100_90', path=정부ㆍ재정/국세통계/국세통계(~2010)/부가가치세): ConnectionError: HTTPSConnectionPool(host='kosis.kr', port=443): Max retries exceeded with url: /openapi/statisticsList.do?method=getList&apiKey=ZTFiMTMzZDliNDQyYmRlMWI5MjJjMmUxNzgyODg3NGM%3D&vwCd=MT_ZTITLE&parentListId=133_13301_100_90&format=json (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7da5c8d13e90>: Failed to resolve 'kosis.kr' ([Errno -5] No address associated with hostname)"))
실패 (parent_id='133_13301_100_70', path=정부ㆍ재정/국세통계/국세통계(~2010)/종합부동산세): ConnectionError: HTTPSConnectionPool(host='kosis.kr', port=443): Max retries exceeded with url: /openapi/statisticsList.do?method=getList&apiKey=ZTFiMTMzZDliNDQyYmRlMWI5MjJjMmUxNzgyODg3NGM%3D&vwCd=MT_ZTITLE&parentListId=133_13301_100_70&format=json (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7da5c8d11a60>: Failed to resolve 'kosis.kr' ([Errno -5] No address associated with hostname)"))
진행: 카테고리 호출 660개 완료, 지금까지 표 4376개, 대기 중인 카테고리 7개
실패 (parent_id='133_13301_200_120_10', path=정부ㆍ재정/국세통계/국세통계(~최근)/국제조세/외국법인 현황): ConnectionError: HTTPSConnectionPool(host='kosis.kr', port=443): Max retries exceeded with url: /openapi/statisticsList.do?method=getList&apiKey=ZTFiMTMzZDliNDQyYmRlMWI5MjJjMmUxNzgyODg3NGM%3D&vwCd=MT_ZTITLE&parentListId=133_13301_200_120_10&format=json (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7da5c8d36630>: Failed to resolve 'kosis.kr' ([Errno -5] No address associated with hostname)"))
진행: 카테고리 호출 680개 완료, 지금까지 표 4555개, 대기 중인 카테고리 15개
진행: 카테고리 호출 700개 완료, 지금까지 표 4702개, 대기 중인 카테고리 15개
진행: 카테고리 호출 720개 완료, 지금까지 표 4838개, 대기 중인 카테고리 12개
실패 (parent_id='133_13301_200_30_30', path=정부ㆍ재정/국세통계/국세통계(~최근)/종합소득세/종합소득세 확정신고 인원 현황): ConnectionError: HTTPSConnectionPool(host='kosis.kr', port=443): Max retries exceeded with url: /openapi/statisticsList.do?method=getList&apiKey=ZTFiMTMzZDliNDQyYmRlMWI5MjJjMmUxNzgyODg3NGM%3D&vwCd=MT_ZTITLE&parentListId=133_13301_200_30_30&format=json (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7da5c8d40ec0>: Failed to resolve 'kosis.kr' ([Errno -5] No address associated with hostname)"))
실패 (parent_id='133_13301_200_30_10', path=정부ㆍ재정/국세통계/국세통계(~최근)/종합소득세/종합소득세 확정신고 현황): ConnectionError: HTTPSConnectionPool(host='kosis.kr', port=443): Max retries exceeded with url: /openapi/statisticsList.do?method=getList&apiKey=ZTFiMTMzZDliNDQyYmRlMWI5MjJjMmUxNzgyODg3NGM%3D&vwCd=MT_ZTITLE&parentListId=133_13301_200_30_10&format=json (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7da5c8d42750>: Failed to resolve 'kosis.kr' ([Errno -5] No address associated with hostname)"))
진행: 카테고리 호출 740개 완료, 지금까지 표 4956개, 대기 중인 카테고리 11개
표 5000개 상한에 도달해서 멈춥니다.

완료: 표 5002개 발견, 카테고리 노드 753개, API 호출 750회, 키워드로 건너뛴 대분류 24개
저장: kosis_full_catalog.csv

In [13]:
# 2) enrichment - 새 표만 처리됨
!python enrich_kosis_catalog_meta.py --input kosis_full_catalog.csv \
    --output kosis_metadata_summary_enriched.csv

이어받기: 34개 표는 이미 완료되어 건너뜁니다.
[20/10040] 진행: 성공 20 | 실패 0 | 건너뜀 0
[40/10040] 진행: 성공 40 | 실패 0 | 건너뜀 0
[60/10040] 진행: 성공 60 | 실패 0 | 건너뜀 0
[80/10040] 진행: 성공 80 | 실패 0 | 건너뜀 0
[100/10040] 진행: 성공 100 | 실패 0 | 건너뜀 0
[120/10040] 진행: 성공 120 | 실패 0 | 건너뜀 0
[140/10040] 진행: 성공 140 | 실패 0 | 건너뜀 0
[160/10040] 진행: 성공 160 | 실패 0 | 건너뜀 0
[180/10040] 진행: 성공 180 | 실패 0 | 건너뜀 0
[200/10040] 진행: 성공 200 | 실패 0 | 건너뜀 0
[220/10040] 진행: 성공 220 | 실패 0 | 건너뜀 0
[240/10040] 진행: 성공 240 | 실패 0 | 건너뜀 0
[260/10040] 진행: 성공 260 | 실패 0 | 건너뜀 0
[280/10040] 진행: 성공 280 | 실패 0 | 건너뜀 0
[300/10040] 진행: 성공 300 | 실패 0 | 건너뜀 0
[320/10040] 진행: 성공 320 | 실패 0 | 건너뜀 0
[340/10040] 진행: 성공 340 | 실패 0 | 건너뜀 0
[360/10040] 진행: 성공 360 | 실패 0 | 건너뜀 0
[380/10040] 진행: 성공 380 | 실패 0 | 건너뜀 0
[400/10040] 진행: 성공 400 | 실패 0 | 건너뜀 0
[420/10040] 진행: 성공 420 | 실패 0 | 건너뜀 0
[440/10040] 진행: 성공 440 | 실패 0 | 건너뜀 0
[460/10040] 진행: 성공 460 | 실패 0 | 건너뜀 0
[480/10040] 진행: 성공 480 | 실패 0 | 건너뜀 0
[500/10040] 진행: 성공 500 | 실패 0 | 건너뜀 0
[520/10040] 진행: 성공 520 | 실패 0 | 건너뜀 0
[540/10040] 진행: 성공 540 | 실패 0 | 건너뜀 0
[560/10040] 진행: 성공 560 | 실패 0 | 건너뜀 0
[580/10040] 진행: 성공 580 | 실패 0 | 건너뜀 0
[600/10040] 진행: 성공 600 | 실패 0 | 건너뜀 0
[620/10040] 진행: 성공 620 | 실패 0 | 건너뜀 0
[640/10040] 진행: 성공 640 | 실패 0 | 건너뜀 0
[660/10040] 진행: 성공 660 | 실패 0 | 건너뜀 0
[680/10040] 진행: 성공 680 | 실패 0 | 건너뜀 0
[700/10040] 진행: 성공 700 | 실패 0 | 건너뜀 0
[720/10040] 진행: 성공 720 | 실패 0 | 건너뜀 0
[740/10040] 진행: 성공 740 | 실패 0 | 건너뜀 0
[760/10040] 진행: 성공 760 | 실패 0 | 건너뜀 0
[780/10040] 진행: 성공 780 | 실패 0 | 건너뜀 0
[800/10040] 진행: 성공 800 | 실패 0 | 건너뜀 0
[820/10040] 진행: 성공 820 | 실패 0 | 건너뜀 0
[840/10040] 진행: 성공 840 | 실패 0 | 건너뜀 0
[860/10040] 진행: 성공 860 | 실패 0 | 건너뜀 0
[880/10040] 진행: 성공 880 | 실패 0 | 건너뜀 0
[900/10040] 진행: 성공 900 | 실패 0 | 건너뜀 0
[920/10040] 진행: 성공 920 | 실패 0 | 건너뜀 0
[940/10040] 진행: 성공 940 | 실패 0 | 건너뜀 0
[960/10040] 진행: 성공 960 | 실패 0 | 건너뜀 0
[980/10040] 진행: 성공 980 | 실패 0 | 건너뜀 0
[1000/10040] 진행: 성공 1000 | 실패 0 | 건너뜀 0
[1020/10040] 진행: 성공 1020 | 실패 0 | 건너뜀 0
[1040/10040] 진행: 성공 1040 | 실패 0 | 건너뜀 0
[1060/10040] 진행: 성공 1060 | 실패 0 | 건너뜀 0
[1080/10040] 진행: 성공 1080 | 실패 0 | 건너뜀 0
[1100/10040] 진행: 성공 1100 | 실패 0 | 건너뜀 0
[1120/10040] 진행: 성공 1120 | 실패 0 | 건너뜀 0
[1140/10040] 진행: 성공 1140 | 실패 0 | 건너뜀 0
[1160/10040] 진행: 성공 1160 | 실패 0 | 건너뜀 0
[1180/10040] 진행: 성공 1180 | 실패 0 | 건너뜀 0
[1200/10040] 진행: 성공 1200 | 실패 0 | 건너뜀 0
[1220/10040] 진행: 성공 1220 | 실패 0 | 건너뜀 0
[1240/10040] 진행: 성공 1240 | 실패 0 | 건너뜀 0
[1260/10040] 진행: 성공 1260 | 실패 0 | 건너뜀 0
[1280/10040] 진행: 성공 1280 | 실패 0 | 건너뜀 0
[1300/10040] 진행: 성공 1300 | 실패 0 | 건너뜀 0
[1320/10040] 진행: 성공 1320 | 실패 0 | 건너뜀 0
[1340/10040] 진행: 성공 1340 | 실패 0 | 건너뜀 0
[1360/10040] 진행: 성공 1360 | 실패 0 | 건너뜀 0
[1380/10040] 진행: 성공 1380 | 실패 0 | 건너뜀 0
[1400/10040] 진행: 성공 1400 | 실패 0 | 건너뜀 0
[1420/10040] 진행: 성공 1420 | 실패 0 | 건너뜀 0
[1440/10040] 진행: 성공 1440 | 실패 0 | 건너뜀 0
[1460/10040] 진행: 성공 1460 | 실패 0 | 건너뜀 0
[1480/10040] 진행: 성공 1480 | 실패 0 | 건너뜀 0
[1500/10040] 진행: 성공 1500 | 실패 0 | 건너뜀 0
[1520/10040] 진행: 성공 1520 | 실패 0 | 건너뜀 0
[1540/10040] 진행: 성공 1540 | 실패 0 | 건너뜀 0
[1560/10040] 진행: 성공 1560 | 실패 0 | 건너뜀 0
[1580/10040] 진행: 성공 1580 | 실패 0 | 건너뜀 0
[1600/10040] 진행: 성공 1600 | 실패 0 | 건너뜀 0
[1620/10040] 진행: 성공 1620 | 실패 0 | 건너뜀 0
[1640/10040] 진행: 성공 1640 | 실패 0 | 건너뜀 0
[1660/10040] 진행: 성공 1660 | 실패 0 | 건너뜀 0
[1680/10040] 진행: 성공 1680 | 실패 0 | 건너뜀 0
[1700/10040] 진행: 성공 1700 | 실패 0 | 건너뜀 0
[1720/10040] 진행: 성공 1720 | 실패 0 | 건너뜀 0
[1740/10040] 진행: 성공 1740 | 실패 0 | 건너뜀 0
[1760/10040] 진행: 성공 1760 | 실패 0 | 건너뜀 0
[1780/10040] 진행: 성공 1780 | 실패 0 | 건너뜀 0
[1800/10040] 진행: 성공 1800 | 실패 0 | 건너뜀 0
[1820/10040] 진행: 성공 1820 | 실패 0 | 건너뜀 0
[1840/10040] 진행: 성공 1840 | 실패 0 | 건너뜀 0
[1860/10040] 진행: 성공 1860 | 실패 0 | 건너뜀 0
[1880/10040] 진행: 성공 1880 | 실패 0 | 건너뜀 0
[1900/10040] 진행: 성공 1900 | 실패 0 | 건너뜀 0
[1920/10040] 진행: 성공 1920 | 실패 0 | 건너뜀 0
[1940/10040] 진행: 성공 1940 | 실패 0 | 건너뜀 0
[1960/10040] 진행: 성공 1960 | 실패 0 | 건너뜀 0
[1980/10040] 진행: 성공 1980 | 실패 0 | 건너뜀 0
[2000/10040] 진행: 성공 2000 | 실패 0 | 건너뜀 0
[2020/10040] 진행: 성공 2020 | 실패 0 | 건너뜀 0

중단됨 - 지금까지 처리한 2024건은 kosis_metadata_summary_enriched.csv 에 저장합니다.

완료: 성공 2024 | 실패 0 | 건너뜀(이미 완료) 0
저장: kosis_metadata_summary_enriched.csv

In [ ]:
!python filter_catalog_by_relevance.py \
    --catalog kosis_full_catalog.csv \
    --claims kosis_ready_plus_improvable.csv \
    --output kosis_full_catalog_trimmed.csv \
    --dropped-output kosis_full_catalog_dropped.csv

claim 142건에서 뽑은 키워드 251개
생성: kosis_full_catalog_trimmed.csv
전체 10074개 표 중 유지 10074개, 제거 0개
제거된 표 목록(참고용): kosis_full_catalog_dropped.csv

In [14]:
!python enrich_kosis_catalog_meta.py \
    --input kosis_full_catalog_trimmed.csv \
    --output kosis_metadata_summary_enriched.csv

Traceback (most recent call last):
  File "/content/enrich_kosis_catalog_meta.py", line 229, in <module>
    main()
  File "/content/enrich_kosis_catalog_meta.py", line 225, in main
    run(args)
  File "/content/enrich_kosis_catalog_meta.py", line 108, in run
    tables = read_csv(args.input)
             ^^^^^^^^^^^^^^^^^^^^
  File "/content/enrich_kosis_catalog_meta.py", line 37, in read_csv
    with open(path, encoding="utf-8-sig", newline="") as file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'kosis_full_catalog_trimmed.csv'

In [ ]:

# 3) 임베딩 - 새 표만 처리됨
!python embed_kosis_catalog_local.py --catalog kosis_metadata_summary_enriched.csv \
    --output kosis_stat_catalog_embeddings_v2.csv

[1/10030] OK 174/DT_163002_B002 (dim=1024)
[2/10030] OK 174/DT_163002_B0021 (dim=1024)
[3/10030] OK 174/DT_163002_B003 (dim=1024)
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 787, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 464, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 1093, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connection.py", line 790, in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connection.py", line 969, in _ssl_wrap_socket_and_match_hostname
    ssl_sock = ssl_wrap_socket(
               ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/urllib3/util/ssl_.py", line 480, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/urllib3/util/ssl_.py", line 524, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/ssl.py", line 455, in wrap_socket
    return self.sslsocket_class._create(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/ssl.py", line 1041, in _create
    self.do_handshake()
  File "/usr/lib/python3.12/ssl.py", line 1319, in do_handshake
    self._sslobj.do_handshake()
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/content/embed_kosis_catalog_local.py", line 113, in <module>
    main()
  File "/content/embed_kosis_catalog_local.py", line 109, in main
    run(args)
  File "/content/embed_kosis_catalog_local.py", line 81, in run
    embedding = call_embedding(key, text)
                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/content/embed_kosis_catalog.py", line 84, in call_embedding
    r = requests.post(EMBED_URL, headers=headers, json={"text": text}, timeout=30)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/requests/api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 856, in urlopen
    conn.close()
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connection.py", line 371, in close
    super().close()
  File "/usr/lib/python3.12/http/client.py", line 1035, in close
    def close(self):

KeyboardInterrupt
^C

In [10]:
import pandas as pd
df = pd.read_csv("kosis_full_catalog_trimmed.csv")
# 겹치는 키워드가 1개뿐인 것 제외 (덜 확실한 매칭)
df["_kw_count"] = df["_matched_keywords"].fillna("").apply(lambda x: len(x.split(",")) if x else 0)
df_strict = df[df["_kw_count"] >= 2]
df_strict.to_csv("kosis_full_catalog_trimmed_strict.csv", index=False, encoding="utf-8-sig")
print(len(df), "->", len(df_strict))

FileNotFoundError: [Errno 2] No such file or directory: 'kosis_full_catalog_trimmed.csv'

In [9]:
!python enrich_kosis_catalog_meta.py \
    --input kosis_full_catalog_trimmed.csv \
    --output kosis_metadata_summary_enriched.csv \
    --limit 300

Traceback (most recent call last):
  File "/content/enrich_kosis_catalog_meta.py", line 229, in <module>
    main()
  File "/content/enrich_kosis_catalog_meta.py", line 225, in main
    run(args)
  File "/content/enrich_kosis_catalog_meta.py", line 108, in run
    tables = read_csv(args.input)
             ^^^^^^^^^^^^^^^^^^^^
  File "/content/enrich_kosis_catalog_meta.py", line 37, in read_csv
    with open(path, encoding="utf-8-sig", newline="") as file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'kosis_full_catalog_trimmed.csv'

In [ ]:
!python filter_catalog_by_relevance.py \
    --catalog kosis_full_catalog.csv \
    --claims kosis_ready_plus_improvable.csv \
    --output kosis_full_catalog_trimmed.csv \
    --dropped-output kosis_full_catalog_dropped.csv

claim 142건에서 뽑은 키워드 251개
생성: kosis_full_catalog_trimmed.csv
전체 10074개 표 중 유지 10074개, 제거 0개
제거된 표 목록(참고용): kosis_full_catalog_dropped.csv

In [ ]:
# 1) 필터 다시 (이번엔 실제로 걸러질 겁니다)
!python filter_catalog_by_relevance.py \
    --catalog kosis_full_catalog.csv \
    --claims kosis_ready_plus_improvable.csv \
    --output kosis_full_catalog_trimmed.csv \
    --dropped-output kosis_full_catalog_dropped.csv

claim 142건에서 뽑은 키워드 229개
생성: kosis_full_catalog_trimmed.csv
전체 10074개 표 중 유지 5282개, 제거 4792개
제거된 표 목록(참고용): kosis_full_catalog_dropped.csv

In [ ]:


# 4) meta-index - 새 표만 처리됨 (같은 kosis_meta_index_v2.csv에 이어붙임)
!python build_kosis_meta_index.py --catalog kosis_metadata_summary_enriched.csv \
    --output kosis_meta_index_v2.csv

이어받기: kosis_meta_index_v2.csv 에 이미 있는 2075개 표는 건너뜁니다 (카탈로그에 새로 추가된 표만 처리).
[1/10065] OK 174/DT_163002_B002 직종별 현원 총괄 (25행)
[2/10065] OK 174/DT_163002_B0021 국가공무원 직종별 현원 (22행)
[3/10065] OK 174/DT_163002_B003 직종별 현원 : 행정·기술·관리운영직 (16행)
[4/10065] OK 174/DT_163002_B0031 직종별 현원 : 일반계약직 (14행)
[5/10065] OK 174/DT_163002_B004 직종별 현원 : 우정직 (14행)
Traceback (most recent call last):
  File "/content/build_kosis_meta_index.py", line 143, in <module>
    main()
  File "/content/build_kosis_meta_index.py", line 139, in main
    run(args)
  File "/content/build_kosis_meta_index.py", line 87, in run
    meta_rows = get_meta(org_id, tbl_id, meta_type="ITM")
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/content/kosis_api_test.py", line 111, in get_meta
    res = requests.get(META_URL, params=params, timeout=10)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 787, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 464, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 1093, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connection.py", line 753, in connect
    self.sock = sock = self._new_conn()
                       ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connection.py", line 198, in _new_conn
    sock = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
KeyboardInterrupt
^C

In [ ]:

df_enriched = pd.read_csv("kosis_metadata_summary_enriched.csv")
df_trimmed = pd.read_csv("kosis_full_catalog_trimmed.csv")  # 관련 있는 것만 걸러진 목록

keep_keys = set(zip(df_trimmed["org_id"].astype(str), df_trimmed["tbl_id"].astype(str)))
df_enriched_filtered = df_enriched[
    df_enriched.apply(lambda r: (str(r["ORG_ID"]), str(r["TBL_ID"])) in keep_keys, axis=1)
]
df_enriched_filtered.to_csv("kosis_metadata_summary_enriched_filtered.csv", index=False, encoding="utf-8-sig")
print(len(df_enriched), "->", len(df_enriched_filtered))

10065 -> 5282

In [ ]:
df_meta = pd.read_csv("kosis_meta_index_v2.csv")
df_meta_filtered = df_meta[
    df_meta.apply(lambda r: (str(r["org_id"]), str(r["tbl_id"])) in keep_keys, axis=1)
]
df_meta_filtered.to_csv("kosis_meta_index_v2_filtered.csv", index=False, encoding="utf-8-sig")
print(len(df_meta), "->", len(df_meta_filtered))

145139 -> 0

In [ ]:
df_trimmed = pd.read_csv("kosis_full_catalog_trimmed.csv")
df_meta = pd.read_csv("kosis_meta_index_v2.csv")

print("trimmed 컬럼:", df_trimmed.columns.tolist())
print("meta 컬럼:", df_meta.columns.tolist())
print()
print("trimmed org_id/tbl_id 샘플:")
print(df_trimmed[["org_id","tbl_id"]].head(3))
print(df_trimmed.dtypes[["org_id","tbl_id"]])
print()
print("meta org_id/tbl_id 샘플:")
print(df_meta[["org_id","tbl_id"]].head(3))
print(df_meta.dtypes[["org_id","tbl_id"]])

trimmed 컬럼: ['org_id', 'tbl_id', 'tbl_nm', 'category_path', 'depth', '_matched_keywords']
meta 컬럼: ['OBJ_ID', 'TBL_ID', 'UNIT_ID', 'ORG_ID', 'OBJ_NM', 'ITM_NM', 'UNIT_ENG_NM', 'ITM_ID', 'UNIT_NM', 'OBJ_NM_ENG', 'org_id', 'tbl_id', 'OBJ_ID_SN', 'ITM_NM_ENG', 'UP_ITM_ID']

trimmed org_id/tbl_id 샘플:
   org_id     tbl_id
0     101  DT_FR0001
1     101  DT_FR0002
2     101  DT_FR0003
org_id     int64
tbl_id    object
dtype: object

meta org_id/tbl_id 샘플:
   org_id           tbl_id
0     102  DT_AS10203-N001
1     102  DT_AS10203-N001
2     102  DT_AS10203-N001
org_id     int64
tbl_id    object
dtype: object

## 3. 입력 파일 지정

업로드한 기사 원문 CSV 파일명으로 아래 변수를 수정하세요.

In [ ]:
ARTICLES_CSV = "articles.csv"  # 업로드한 실제 파일명으로 수정

## 4. 실행 (HCX 호출)

- `LIMIT`: 앞에서부터 N개 기사만 처리. `0`이면 전체 처리.
- `MAX_CHARS`: 기사 본문이 이보다 길면 문단 단위로 나눠서(chunk) 여러 번 호출합니다.
  chunk로 나뉘면 "기사 전체 맥락" 효과가 chunk 범위로 줄어드니, 웬만하면 기사 하나가
  통째로 들어갈 수 있는 값으로 넉넉히 두는 걸 권장합니다.
- 먼저 `LIMIT`을 작게 두고 결과를 확인한 다음 `0`으로 바꿔 전체 처리하세요.

In [ ]:
LIMIT = 0          # 0 = 전체 처리
MAX_CHARS = 3000   # 기사 본문 chunk 최대 길이

!python extract_article_claims_hcx.py \
    --input {ARTICLES_CSV} \
    --output hcx_article_extracted.csv \
    --limit {LIMIT} \
    --max-chars {MAX_CHARS}

이어받기: 0개 기사 완료됨
[A0001] ok (claim 0건, 행 0개, chunk 1개, grounding 실패 0건)
[A0002] ok (claim 0건, 행 0개, chunk 1개, grounding 실패 0건)
[A0003] ok (claim 1건, 행 3개, chunk 1개, grounding 실패 1건)
[A0004] ok (claim 4건, 행 9개, chunk 1개, grounding 실패 0건)
[A0005] ok (claim 1건, 행 1개, chunk 1개, grounding 실패 0건)
[A0006] 실패: JSONDecodeError: Expecting ',' delimiter: line 402 column 6 (char 12277)
[A0007] ok (claim 5건, 행 7개, chunk 1개, grounding 실패 1건)
[A0008] ok (claim 2건, 행 2개, chunk 1개, grounding 실패 0건)
[A0009] 실패: JSONDecodeError: Expecting ',' delimiter: line 353 column 6 (char 11612)
[A0010] 실패: JSONDecodeError: Expecting ',' delimiter: line 398 column 6 (char 12349)
[A0011] ok (claim 1건, 행 1개, chunk 1개, grounding 실패 0건)
[A0012] ok (claim 1건, 행 2개, chunk 1개, grounding 실패 0건)
[A0013] ok (claim 2건, 행 2개, chunk 1개, grounding 실패 0건)
[A0014] ok (claim 0건, 행 0개, chunk 1개, grounding 실패 0건)
[A0015] ok (claim 1건, 행 2개, chunk 1개, grounding 실패 0건)
[A0016] ok (claim 0건, 행 0개, chunk 1개, grounding 실패 0건)
[A0017] ok (claim 0건, 행 0개, chunk 1개, grounding 실패 0건)
[A0018] ok (claim 1건, 행 3개, chunk 1개, grounding 실패 1건)
[A0019] ok (claim 6건, 행 8개, chunk 1개, grounding 실패 6건)
[A0020] ok (claim 5건, 행 13개, chunk 1개, grounding 실패 3건)
[A0021] ok (claim 0건, 행 0개, chunk 1개, grounding 실패 0건)
[A0022] ok (claim 0건, 행 0개, chunk 1개, grounding 실패 0건)
[A0023] ok (claim 9건, 행 25개, chunk 1개, grounding 실패 2건)
[A0024] 실패: JSONDecodeError: Expecting ',' delimiter: line 422 column 4 (char 13174)
[A0025] ok (claim 0건, 행 0개, chunk 1개, grounding 실패 0건)
[A0026] ok (claim 1건, 행 1개, chunk 1개, grounding 실패 0건)
[A0027] ok (claim 4건, 행 4개, chunk 1개, grounding 실패 2건)
[A0028] ok (claim 6건, 행 10개, chunk 1개, grounding 실패 0건)
[A0029] ok (claim 1건, 행 2개, chunk 1개, grounding 실패 0건)
[A0030] ok (claim 4건, 행 8개, chunk 1개, grounding 실패 1건)
[A0031] ok (claim 3건, 행 6개, chunk 1개, grounding 실패 0건)
[A0032] ok (claim 3건, 행 6개, chunk 1개, grounding 실패 2건)
[A0033] ok (claim 0건, 행 0개, chunk 1개, grounding 실패 0건)
[A0034] ok (claim 1건, 행 2개, chunk 1개, grounding 실패 0건)
[A0035] ok (claim 0건, 행 0개, chunk 1개, grounding 실패 0건)
[A0036] ok (claim 0건, 행 0개, chunk 1개, grounding 실패 0건)
[A0037] ok (claim 0건, 행 0개, chunk 1개, grounding 실패 0건)
[A0038] ok (claim 0건, 행 0개, chunk 1개, grounding 실패 0건)
[A0039] ok (claim 1건, 행 1개, chunk 1개, grounding 실패 0건)
[A0040] ok (claim 1건, 행 4개, chunk 1개, grounding 실패 0건)
[A0041] 실패: JSONDecodeError: Expecting ',' delimiter: line 379 column 6 (char 11927)
[A0042] ok (claim 0건, 행 0개, chunk 1개, grounding 실패 0건)
[A0043] ok (claim 0건, 행 0개, chunk 1개, grounding 실패 0건)
[A0044] ok (claim 0건, 행 0개, chunk 1개, grounding 실패 0건)
[A0045] ok (claim 1건, 행 5개, chunk 1개, grounding 실패 0건)
[A0046] ok (claim 0건, 행 0개, chunk 1개, grounding 실패 0건)
[A0047] ok (claim 0건, 행 0개, chunk 1개, grounding 실패 0건)
[A0048] ok (claim 0건, 행 0개, chunk 1개, grounding 실패 0건)
[A0049] ok (claim 7건, 행 8개, chunk 1개, grounding 실패 0건)
[A0050] ok (claim 1건, 행 3개, chunk 1개, grounding 실패 0건)
완료 → hcx_article_extracted.csv

In [ ]:
import os
print(os.listdir())

['.config', '.ipynb_checkpoints', '뉴스_데이터_규칙기반정제Top50.csv', 'extract_article_claims_hcx.py', 'extract_hcx .py', 'sample_data']

## 5. 결과 확인

In [ ]:
import pandas as pd

df = pd.read_csv("hcx_article_extracted.csv")
print(len(df), "행 (claim당 measurement 여러 행일 수 있음)")
print()
print("기사 수:", df["article_id"].nunique(), "| claim 수:", df["claim_id"].nunique())
print("grounding 실패(claim_grounded=N):", (df["claim_grounded"] == "N").sum(), "건")
print("규칙 fallback 보정된 행:", (df["measurement_source"] == "rule_fallback").sum(), "건")
print("needs_review=Y:", (df["needs_review"] == "Y").sum(), "건")
df.head(10)

138 행 (claim당 measurement 여러 행일 수 있음)

기사 수: 26 | claim 수: 73
grounding 실패(claim_grounded=N): 32 건
규칙 fallback 보정된 행: 41 건
needs_review=Y: 105 건

,claim_id,claim_measurement_id,article_id,title,date,url,claim_text,prev_sentence,next_sentence,claim_domain_scope,...,review_reason,measurement_repaired,measurement_fallback_count,measurement_binding_fallback_count,extraction_model,prompt_version,extracted_at,claim_grounded,extraction_scope,chunk_index
0,A0003-c001,A0003-c001-m1,A0003,최저임금 1만30원으로 인상… 육아휴직 급여 최대 월 250만원,2025-01-01,https://www.chosun.com/economy/economy_general...,최저임금이 시간당 1만30원 =최저임금이 시간당 9860원에서 1만30원으로 1.7...,-,-,국내공식통계,...,measurement_rule_fallback:1;measurement_bindin...,Y,1,1,HCX-007,article-combined-v1.0,2026-07-30,N,article_combined,0
1,A0003-c001,A0003-c001-m2,A0003,최저임금 1만30원으로 인상… 육아휴직 급여 최대 월 250만원,2025-01-01,https://www.chosun.com/economy/economy_general...,최저임금이 시간당 1만30원 =최저임금이 시간당 9860원에서 1만30원으로 1.7...,-,-,국내공식통계,...,measurement_rule_fallback:1;measurement_bindin...,Y,1,1,HCX-007,article-combined-v1.0,2026-07-30,N,article_combined,0
2,A0003-c001,A0003-c001-m3,A0003,최저임금 1만30원으로 인상… 육아휴직 급여 최대 월 250만원,2025-01-01,https://www.chosun.com/economy/economy_general...,최저임금이 시간당 1만30원 =최저임금이 시간당 9860원에서 1만30원으로 1.7...,-,-,국내공식통계,...,measurement_rule_fallback:1;measurement_bindin...,Y,1,1,HCX-007,article-combined-v1.0,2026-07-30,N,article_combined,0
3,A0004-c001,A0004-c001-m1,A0004,‘직원 한 명에 로봇 수십 대’… 이젠 로봇이 공장 움직인다,2025-01-01,https://www.chosun.com/economy/economy_general...,국제로봇연맹(IFR)에 따르면 2023년 우리나라는 직원 1만명당 로봇 1012대를...,-,-,국내공식통계,...,measurement_rule_fallback:1,Y,1,0,HCX-007,article-combined-v1.0,2026-07-30,Y,article_combined,0
4,A0004-c001,A0004-c001-m2,A0004,‘직원 한 명에 로봇 수십 대’… 이젠 로봇이 공장 움직인다,2025-01-01,https://www.chosun.com/economy/economy_general...,국제로봇연맹(IFR)에 따르면 2023년 우리나라는 직원 1만명당 로봇 1012대를...,-,-,국내공식통계,...,measurement_rule_fallback:1,Y,1,0,HCX-007,article-combined-v1.0,2026-07-30,Y,article_combined,0
5,A0004-c002,A0004-c002-m1,A0004,‘직원 한 명에 로봇 수십 대’… 이젠 로봇이 공장 움직인다,2025-01-01,https://www.chosun.com/economy/economy_general...,전 세계 평균(1만명당 162대)의 6배가 넘는 수치다.,-,-,국내공식통계,...,measurement_rule_fallback:2,Y,2,0,HCX-007,article-combined-v1.0,2026-07-30,Y,article_combined,0
6,A0004-c002,A0004-c002-m2,A0004,‘직원 한 명에 로봇 수십 대’… 이젠 로봇이 공장 움직인다,2025-01-01,https://www.chosun.com/economy/economy_general...,전 세계 평균(1만명당 162대)의 6배가 넘는 수치다.,-,-,국내공식통계,...,measurement_rule_fallback:2,Y,2,0,HCX-007,article-combined-v1.0,2026-07-30,Y,article_combined,0
7,A0004-c002,A0004-c002-m3,A0004,‘직원 한 명에 로봇 수십 대’… 이젠 로봇이 공장 움직인다,2025-01-01,https://www.chosun.com/economy/economy_general...,전 세계 평균(1만명당 162대)의 6배가 넘는 수치다.,-,-,국내공식통계,...,measurement_rule_fallback:2,Y,2,0,HCX-007,article-combined-v1.0,2026-07-30,Y,article_combined,0
8,A0004-c003,A0004-c003-m1,A0004,‘직원 한 명에 로봇 수십 대’… 이젠 로봇이 공장 움직인다,2025-01-01,https://www.chosun.com/economy/economy_general...,전 세계 평균(1만명당 162대)의 6배가 넘는 수치다.,-,-,국내공식통계,...,measurement_rule_fallback:1,Y,1,0,HCX-007,article-combined-v1.0,2026-07-30,Y,article_combined,0
9,A0004-c003,A0004-c003-m2,A0004,‘직원 한 명에 로봇 수십 대’… 이젠 로봇이 공장 움직인다,2025-01-01,https://www.chosun.com/economy/economy_general...,전 세계 평균(1만명당 162대)의 6배가 넘는 수치다.,-,-,국내공식통계,...,measurement_rule_fallback:1,Y,1,0,HCX-007,article-combined-v1.0,2026-07-30,Y,article_combined,0

### 검토가 필요한 행만 모아보기

`claim_grounded=N`(기사에 없는 문장을 지어낸 경우)이나 `needs_review=Y`인 행은
우선적으로 사람이 확인하는 걸 권장합니다.

In [ ]:
review_cols = ["claim_id", "claim_text", "value", "unit", "measurement_indicator",
               "measurement_period", "claim_grounded", "needs_review", "review_reason"]

df_review = df[(df["claim_grounded"] == "N") | (df["needs_review"] == "Y")]
print(len(df_review), "건 검토 필요")
df_review[review_cols]

106 건 검토 필요

,claim_id,claim_text,value,unit,measurement_indicator,measurement_period,claim_grounded,needs_review,review_reason
0,A0003-c001,최저임금이 시간당 1만30원 =최저임금이 시간당 9860원에서 1만30원으로 1.7...,10030,원,최저임금,2025,N,Y,measurement_rule_fallback:1;measurement_bindin...
1,A0003-c001,최저임금이 시간당 1만30원 =최저임금이 시간당 9860원에서 1만30원으로 1.7...,9860,원,최저임금,2025,N,Y,measurement_rule_fallback:1;measurement_bindin...
2,A0003-c001,최저임금이 시간당 1만30원 =최저임금이 시간당 9860원에서 1만30원으로 1.7...,1.7,%,최저임금,2025,N,Y,measurement_rule_fallback:1;measurement_bindin...
3,A0004-c001,국제로봇연맹(IFR)에 따르면 2023년 우리나라는 직원 1만명당 로봇 1012대를...,1012,대,로봇 밀도,2023,Y,Y,measurement_rule_fallback:1
4,A0004-c001,국제로봇연맹(IFR)에 따르면 2023년 우리나라는 직원 1만명당 로봇 1012대를...,10000,명,로봇 밀도,2023,Y,Y,measurement_rule_fallback:1
...,...,...,...,...,...,...,...,...,...
129,A0049-c002,현대건설의 첫 수주 이후 59년 만의 성과다.,59,년,경과 시간,2025,Y,Y,measurement_binding_fallback:1;measurement_per...
134,A0049-c007,오는 3월 최종 계약을 앞둔 24조원 규모 체코 두코바니 원전은 대우건설이 시공할 ...,24000000000000,원,체코 두코바니 원전 수주 예상액,-,Y,Y,measurement_period_ungrounded:1
135,A0050-c001,통계청 자료에 따르면 국내 부업자 수는 2023년 1분기 45만명에서 2024년 1...,550000,명,부업자 수,2024,Y,Y,measurement_rule_fallback:1
136,A0050-c001,통계청 자료에 따르면 국내 부업자 수는 2023년 1분기 45만명에서 2024년 1...,450000,명,부업자 수,2023,Y,Y,measurement_rule_fallback:1
137,A0050-c001,통계청 자료에 따르면 국내 부업자 수는 2023년 1분기 45만명에서 2024년 1...,20,%,부업자 수,2024년 1분기,Y,Y,measurement_rule_fallback:1

## (선택, 고급) 이전 실행 결과와 회귀 비교

프롬프트나 모델을 바꿔가며 재실행할 때, 이전 결과에서 값(value)이 비어 있던
claim들이 이번엔 채워졌는지 확인하고 싶다면 `measurement_regression.py`(문장 단위
파이프라인에서 쓰던 스크립트)를 그대로 재사용할 수 있습니다. `--baseline`에는
**이전 실행 결과 CSV**를 넣으세요. 처음 실행이라 비교 대상이 없다면 건너뛰어도 됩니다.

In [ ]:
# measurement_regression.py 도 업로드했다면 아래 주석을 풀어 사용하세요.
# PREVIOUS_EXTRACTED = "이전_hcx_article_extracted.csv"  # 이전 실행 결과 파일명
#
# !python measurement_regression.py audit \
#     --baseline {PREVIOUS_EXTRACTED} \
#     --candidate hcx_article_extracted.csv \
#     --report audit_report.csv
#
# import json
# df_report = pd.read_csv("audit_report.csv")
# print(df_report["status"].value_counts())
# json.loads(open("audit_report.summary.json", encoding="utf-8").read())

## 6. 결과 다운로드

In [ ]:
from google.colab import files

files.download("hcx_article_extracted.csv")

In [ ]:
from google.colab import files

uploaded = files.upload()  # prepare_kosis_mapping_input.py 선택
print("업로드됨:", list(uploaded.keys()))

Saving prepare_kosis_mapping_input.py to prepare_kosis_mapping_input.py
업로드됨: ['prepare_kosis_mapping_input.py']

In [ ]:
!python prepare_kosis_mapping_input.py \
    --input hcx_extracted.csv \
    --output kosis_ready.csv \
    --rejected-output kosis_rejected.csv

input=421 ready=114 rejected=307
rejection_counts=OUT_OF_KOSIS_SCOPE:136, NOT_KOSIS_VALUE:64, NO_MEASUREMENT:53, PERIOD_MISSING:27, ROLE_NOT_DIRECT_TARGET:16, RANK_NOT_DIRECTLY_COMPARABLE:5, UNIT_UNSUPPORTED:4, BINDING_NOT_CONFIRMED:1, VALUE_MISSING:1
saved=kosis_ready.csv
rejected=kosis_rejected.csv

In [ ]:
import pandas as pd

df_ready = pd.read_csv("kosis_ready.csv")
df_rejected = pd.read_csv("kosis_rejected.csv")

print(f"ready: {len(df_ready)}건 | rejected: {len(df_rejected)}건 "
      f"(전체 {len(df_ready) + len(df_rejected)}건 중 {len(df_ready)/(len(df_ready)+len(df_rejected)):.1%})")
print()
print("배제 사유 분포:")
print(df_rejected["mapping_exclusion_code"].value_counts())

ready: 114건 | rejected: 307건 (전체 421건 중 27.1%)

배제 사유 분포:
mapping_exclusion_code
OUT_OF_KOSIS_SCOPE              136
NOT_KOSIS_VALUE                  64
NO_MEASUREMENT                   53
PERIOD_MISSING                   27
ROLE_NOT_DIRECT_TARGET           16
RANK_NOT_DIRECTLY_COMPARABLE      5
UNIT_UNSUPPORTED                  4
BINDING_NOT_CONFIRMED             1
VALUE_MISSING                     1
Name: count, dtype: int64

In [ ]:
# ready 로 통과한 값 미리보기
cols = ["claim_id", "claim_text", "indicator", "value", "unit", "canonical_unit",
        "semantic_type", "period", "prd_se", "entity_type"]
df_ready[cols]

,claim_id,claim_text,indicator,value,unit,canonical_unit,semantic_type,period,prd_se,entity_type
0,B0006-s002,"지난 1일까지 설선물 매출을 지난 설 동기간과 비교했을 때 롯데백화점은 45%, 신...",설선물 매출 증가율,4.500000e+01,%,%,rate_change,202501,M,item
1,B0006-s002,"지난 1일까지 설선물 매출을 지난 설 동기간과 비교했을 때 롯데백화점은 45%, 신...",설선물 매출 증가율,7.240000e+01,%,%,rate_change,202501,M,item
2,B0006-s002,"지난 1일까지 설선물 매출을 지난 설 동기간과 비교했을 때 롯데백화점은 45%, 신...",설선물 매출 증가율,7.180000e+01,%,%,rate_change,202501,M,item
3,B0006-s002,"지난 1일까지 설선물 매출을 지난 설 동기간과 비교했을 때 롯데백화점은 45%, 신...",설선물 매출 증가율,3.200000e+01,%,%,rate_change,202501,M,item
4,B0006-s011,"롯데백화점은 5일까지 롯데백화점 전점에서 축산, 수산, 청과, 그로서리 등에서 약 ...",설 사전 예약 판매 품목 수,2.300000e+02,개,개,count,202501,M,unspecified
...,...,...,...,...,...,...,...,...,...,...
109,B0046-s005,직전 최저치는 2023년 4분기의 29조8000억원이다.,순자금 운용액,2.980000e+13,원,원,amount,2023,Y,unspecified
110,B0046-s007,통계청에 따르면 작년 3분기 가계소득은 전 분기보다 5.9% 늘었다.,가계소득,5.900000e+00,%,%,rate_change,2024Q3,Q,unspecified
111,B0046-s009,가계 및 비영리단체의 자금 조달액 중 주택 담보대출금도 작년 3분기에 전 분기보다 ...,가계 및 비영리단체의 자금 조달액,1.940000e+13,원,원,amount,2024Q3,Q,item
112,B0047-s009,"종신보험은 보험료 납입 기간이 20~30년인데, 현재 보험료 납입이 끝난 계약은 약...",보험료 납입 완료 계약 건수,3.620000e+06,건,건,count,2025,Y,unspecified
113,B0050-s033,“한국이 겪는 어려움에는 0.7명이라는 낮은 출산율이 영향을 끼쳤다.,출산율,7.000000e-01,명,명,count,2025,Y,unspecified

In [ ]:
# BINDING_NOT_CONFIRMED / PERIODICITY_MISSING 처럼 "개선하면 ready 될 수 있는" 케이스만 모아보기
IMPROVABLE_CODES = {"BINDING_NOT_CONFIRMED", "PERIODICITY_MISSING", "PERIOD_MISSING"}
review_cols = ["claim_id", "claim_text", "value", "unit", "measurement_indicator",
               "measurement_period", "measurement_prd_se", "measurement_binding_source",
               "mapping_exclusion_code", "mapping_exclusion_reason"]

df_improvable = df_rejected[df_rejected["mapping_exclusion_code"].isin(IMPROVABLE_CODES)]
print(len(df_improvable), "건 - 프롬프트/보정 로직 개선 시 ready 로 넘어올 여지 있음")
df_improvable[review_cols]

28 건 - 프롬프트/보정 로직 개선 시 ready 로 넘어올 여지 있음

,claim_id,claim_text,value,unit,measurement_indicator,measurement_period,measurement_prd_se,measurement_binding_source,mapping_exclusion_code,mapping_exclusion_reason
54,B0011-s000,0 작년 4분기 실적 발표 시즌이 다가온 가운데 상장사들의 성적표가 3개월 전보다 ...,16.5,%,영업이익 변화율,-,-,hcx,PERIOD_MISSING,measurement period 없음
60,B0011-s006,3일 기준 증권사 3개 이상이 추정치를 제시한 코스피 상장사 110곳의 총 영업이익...,39653100000000,원,영업이익,-,-,hcx,PERIOD_MISSING,measurement period 없음
63,B0011-s007,"2023년 4분기 영업이익 합 19조7942억원과 비교하면 2배 수준이지만, 비교군...",87,개,영업이익,2024Q4,Q,rule_fallback,BINDING_NOT_CONFIRMED,measurement_binding_source=rule_fallback
71,B0016-s015,지난달 29일 사고 이후 8일간 공항에서 활동한 자원봉사자는 총 5509명으로 집계됐다.,5509,명,자원봉사자 수,-,-,hcx,PERIOD_MISSING,measurement period 없음
77,B0016-s022,"제주도관광협회에 따르면, 제주항공 참사 이튿날인 지난달 30일부터 지난 5일까지 일...",208516,명,관광객 수,-,-,hcx,PERIOD_MISSING,measurement period 없음
78,B0016-s022,"제주도관광협회에 따르면, 제주항공 참사 이튿날인 지난달 30일부터 지난 5일까지 일...",31495,명,감소한 관광객 수,-,-,hcx,PERIOD_MISSING,measurement period 없음
79,B0016-s022,"제주도관광협회에 따르면, 제주항공 참사 이튿날인 지난달 30일부터 지난 5일까지 일...",13.1,%,관광객 감소율,-,-,hcx,PERIOD_MISSING,measurement period 없음
80,B0016-s023,이 가운데 내국인 관광객은 전년 대비 3만7105명(16.7%) 줄었다.,37105,명,내국인 관광객 수,-,-,hcx,PERIOD_MISSING,measurement period 없음
81,B0016-s023,이 가운데 내국인 관광객은 전년 대비 3만7105명(16.7%) 줄었다.,16.7,%,내국인 관광객 증감률,-,-,hcx,PERIOD_MISSING,measurement period 없음
95,B0019-s001,"5일 한국농수산식품유통공사(aT)에 따르면, 지난 3일 기준 배추의 평균 소매가격은...",5027,원,배추 소매가격,-,-,hcx,PERIOD_MISSING,measurement period 없음
96,B0019-s001,"5일 한국농수산식품유통공사(aT)에 따르면, 지난 3일 기준 배추의 평균 소매가격은...",59,%,배추 가격 상승률,-,-,hcx,PERIOD_MISSING,measurement period 없음
97,B0019-s001,"5일 한국농수산식품유통공사(aT)에 따르면, 지난 3일 기준 배추의 평균 소매가격은...",42,%,배추 가격 상승률,-,-,hcx,PERIOD_MISSING,measurement period 없음
99,B0019-s003,"무는 한 개에 3206원으로 1년 전보다 77% 비싸졌고, 평년보다 53% 가격이 ...",3206,원,무 가격,-,-,hcx,PERIOD_MISSING,measurement period 없음
100,B0019-s003,"무는 한 개에 3206원으로 1년 전보다 77% 비싸졌고, 평년보다 53% 가격이 ...",77,%,무 가격 증감률,-,-,hcx,PERIOD_MISSING,measurement period 없음
101,B0019-s003,"무는 한 개에 3206원으로 1년 전보다 77% 비싸졌고, 평년보다 53% 가격이 ...",53,%,무 가격 증감률,-,-,hcx,PERIOD_MISSING,measurement period 없음
111,B0020-s010,대중 수출은 지난 2010년(1168억3800만달러)부터 1000억달러선을 넘어섰고...,100000000000,달러,대중 수출액,-,-,hcx,PERIOD_MISSING,measurement period 없음
124,B0022-s029,"전체 신용카드 이용액은 1년 전 대비 2.8% 늘어났지만, 외식·숙박·오락 소비는 ...",2.8,%,신용카드 이용액,-,-,hcx,PERIOD_MISSING,measurement period 없음
127,B0022-s030,셋째 주 신용카드 소비를 분야별로 보면 숙박 서비스는 1년 전 대비 8.3% 줄었고...,8.3,%,신용카드 소비,-,-,hcx,PERIOD_MISSING,measurement period 없음
128,B0022-s030,셋째 주 신용카드 소비를 분야별로 보면 숙박 서비스는 1년 전 대비 8.3% 줄었고...,5.9,%,신용카드 소비,-,-,hcx,PERIOD_MISSING,measurement period 없음
129,B0022-s030,셋째 주 신용카드 소비를 분야별로 보면 숙박 서비스는 1년 전 대비 8.3% 줄었고...,0.3,%,신용카드 소비,-,-,hcx,PERIOD_MISSING,measurement period 없음
131,B0022-s032,소비 심리를 나타내는 소비자심리지수(CCSI)는 12월 88.4로 전월보다 12.3...,88.4,포인트,소비자심리지수(CCSI),-,-,hcx,PERIOD_MISSING,measurement period 없음
134,B0022-s035,서울 여의도에서 4년째 영업 중인 한 돼지고깃집은 지난달 3일 계엄 사태가 발생한 ...,30,%,점심 손님 비율,-,-,hcx,PERIOD_MISSING,measurement period 없음
135,B0022-s035,서울 여의도에서 4년째 영업 중인 한 돼지고깃집은 지난달 3일 계엄 사태가 발생한 ...,50,%,저녁 손님 비율,-,-,hcx,PERIOD_MISSING,measurement period 없음
146,B0023-s014,한은의 외환보유액 규모는 11월말 기준(4154억달러)로 세계 9위 수준이다.,415400000000,달러,외환보유액 총액,-,-,hcx,PERIOD_MISSING,measurement period 없음
147,B0023-s014,한은의 외환보유액 규모는 11월말 기준(4154억달러)로 세계 9위 수준이다.,9,위,세계 외환보유액 순위,-,-,hcx,PERIOD_MISSING,measurement period 없음
183,B0026-s000,0 우리나라 수출의 20%가량을 맡고 있는 핵심 품목인 반도체의 ‘수출 지형도’가 ...,20,%,반도체 수출 비중,-,-,hcx,PERIOD_MISSING,measurement period 없음
271,B0041-s014,주요 6국 통화 대비 달러 가치를 나타내는 달러 인덱스는 지난주 109대보다는 소폭...,109,대,달러 인덱스,-,-,hcx,PERIOD_MISSING,measurement period 없음
295,B0048-s027,◇원화 환율 1440원대 7일 서울 외환시장에서 달러 대비 원화 환율은 1453.5...,1453.5,원,원화 환율,-,-,hcx,PERIOD_MISSING,measurement period 없음

In [ ]:
import pandas as pd

df_ready = pd.read_csv("kosis_ready.csv")
df_rejected = pd.read_csv("kosis_rejected.csv")

IMPROVABLE_CODES = {"BINDING_NOT_CONFIRMED", "PERIODICITY_MISSING", "PERIOD_MISSING"}
df_improvable = df_rejected[df_rejected["mapping_exclusion_code"].isin(IMPROVABLE_CODES)]

df_merged = pd.concat([df_ready, df_improvable], ignore_index=True)
df_merged.to_csv("kosis_ready_plus_improvable.csv", index=False, encoding="utf-8-sig")

print(f"ready {len(df_ready)}건 + improvable {len(df_improvable)}건 = {len(df_merged)}건")

ready 114건 + improvable 28건 = 142건

In [ ]:

df_enriched = pd.read_csv("kosis_metadata_summary_enriched.csv")
print("전체 표 개수:", len(df_enriched))

df_enriched["top_category"] = df_enriched["category_path"].str.split(" > ").str[0]
print(df_enriched["top_category"].value_counts())

전체 표 개수: 10065
top_category
정부ㆍ재정       5015
도소매ㆍ서비스     4762
소득ㆍ소비ㆍ자산     237
물가            51
Name: count, dtype: int64

In [ ]:

# 예전 배치(무역+금융, 2075개)와 이번 배치(재정+도소매+소득소비+물가, 10065개)를 합침
df_old = pd.read_csv("kosis_metadata_summary_enriched_old.csv")   # 예전 2075개짜리 파일명 확인 필요
df_new = pd.read_csv("kosis_metadata_summary_enriched.csv")       # 지금 10065개
df_combined = pd.concat([df_old, df_new], ignore_index=True).drop_duplicates(subset=["ORG_ID","TBL_ID"])
df_combined.to_csv("kosis_metadata_summary_enriched_combined.csv", index=False, encoding="utf-8-sig")
print(len(df_old), "+", len(df_new), "->", len(df_combined))

# meta-index도 똑같이
df_meta_old = pd.read_csv("kosis_meta_index_old.csv")   # 예전 무역+금융 meta-index 파일명 확인 필요
df_meta_new = pd.read_csv("kosis_meta_index_v2.csv")
df_meta_combined = pd.concat([df_meta_old, df_meta_new], ignore_index=True).drop_duplicates()
df_meta_combined.to_csv("kosis_meta_index_combined.csv", index=False, encoding="utf-8-sig")
print(len(df_meta_old), "+", len(df_meta_new), "->", len(df_meta_combined))

FileNotFoundError: [Errno 2] No such file or directory: 'kosis_metadata_summary_enriched_old.csv'

In [6]:
# 1) 무역+금융만 새로 크롤링 (완전히 새 파일명)
!python crawl_kosis_catalog.py --output kosis_full_catalog_tf.csv \
    --top-category-keywords "무역ㆍ국제수지,금융" --max-tables 3000

# 2) enrichment - 새 파일명으로 (kosis_meta_index_v2.csv는 절대 건드리지 않음)
!python enrich_kosis_catalog_meta.py \
    --input kosis_full_catalog_tf.csv \
    --output kosis_metadata_summary_enriched_tf.csv \
    --meta-index-output kosis_meta_index_tf.csv

크롤링 시작: vw_cd=MT_ZTITLE, max_depth=무제한, top_category_keywords=['무역ㆍ국제수지', '금융'], max_tables=3000
진행: 카테고리 호출 20개 완료, 지금까지 표 102개, 대기 중인 카테고리 15개
진행: 카테고리 호출 40개 완료, 지금까지 표 281개, 대기 중인 카테고리 6개
진행: 카테고리 호출 60개 완료, 지금까지 표 336개, 대기 중인 카테고리 14개
진행: 카테고리 호출 80개 완료, 지금까지 표 380개, 대기 중인 카테고리 18개
진행: 카테고리 호출 100개 완료, 지금까지 표 416개, 대기 중인 카테고리 22개
진행: 카테고리 호출 120개 완료, 지금까지 표 447개, 대기 중인 카테고리 15개
진행: 카테고리 호출 140개 완료, 지금까지 표 499개, 대기 중인 카테고리 15개
진행: 카테고리 호출 160개 완료, 지금까지 표 918개, 대기 중인 카테고리 19개
진행: 카테고리 호출 180개 완료, 지금까지 표 1105개, 대기 중인 카테고리 24개
진행: 카테고리 호출 200개 완료, 지금까지 표 1250개, 대기 중인 카테고리 18개
진행: 카테고리 호출 220개 완료, 지금까지 표 1344개, 대기 중인 카테고리 10개
진행: 카테고리 호출 240개 완료, 지금까지 표 1401개, 대기 중인 카테고리 21개
진행: 카테고리 호출 260개 완료, 지금까지 표 1541개, 대기 중인 카테고리 14개
진행: 카테고리 호출 280개 완료, 지금까지 표 1734개, 대기 중인 카테고리 10개
진행: 카테고리 호출 300개 완료, 지금까지 표 1878개, 대기 중인 카테고리 5개
진행: 카테고리 호출 320개 완료, 지금까지 표 2193개, 대기 중인 카테고리 18개
진행: 카테고리 호출 340개 완료, 지금까지 표 2616개, 대기 중인 카테고리 10개
진행: 카테고리 호출 360개 완료, 지금까지 표 2694개, 대기 중인 카테고리 6개

완료: 표 2755개 발견, 카테고리 노드 373개, API 호출 374회, 키워드로 건너뛴 대분류 28개
저장: kosis_full_catalog_tf.csv
[20/2755] 진행: 성공 20 | 실패 0 | 건너뜀 0
[40/2755] 진행: 성공 40 | 실패 0 | 건너뜀 0
[60/2755] 진행: 성공 60 | 실패 0 | 건너뜀 0
[80/2755] 진행: 성공 80 | 실패 0 | 건너뜀 0
[100/2755] 진행: 성공 100 | 실패 0 | 건너뜀 0
[120/2755] 진행: 성공 120 | 실패 0 | 건너뜀 0
[140/2755] 진행: 성공 140 | 실패 0 | 건너뜀 0
[160/2755] 진행: 성공 160 | 실패 0 | 건너뜀 0
[180/2755] 진행: 성공 180 | 실패 0 | 건너뜀 0
[200/2755] 진행: 성공 200 | 실패 0 | 건너뜀 0
[220/2755] 진행: 성공 220 | 실패 0 | 건너뜀 0
[240/2755] 진행: 성공 240 | 실패 0 | 건너뜀 0
[260/2755] 진행: 성공 260 | 실패 0 | 건너뜀 0
[280/2755] 진행: 성공 280 | 실패 0 | 건너뜀 0
[300/2755] 진행: 성공 300 | 실패 0 | 건너뜀 0
[320/2755] 진행: 성공 320 | 실패 0 | 건너뜀 0
[340/2755] 진행: 성공 340 | 실패 0 | 건너뜀 0
[360/2755] 진행: 성공 360 | 실패 0 | 건너뜀 0
[363/2755] 실패 301/DT_105Y001: JSONDecodeError: Invalid \escape: line 1 column 3211 (char 3210)
[381/2755] 진행: 성공 380 | 실패 1 | 건너뜀 0
[401/2755] 진행: 성공 400 | 실패 1 | 건너뜀 0
[421/2755] 진행: 성공 420 | 실패 1 | 건너뜀 0
[441/2755] 진행: 성공 440 | 실패 1 | 건너뜀 0
[461/2755] 진행: 성공 460 | 실패 1 | 건너뜀 0
[481/2755] 진행: 성공 480 | 실패 1 | 건너뜀 0
[501/2755] 진행: 성공 500 | 실패 1 | 건너뜀 0
[521/2755] 진행: 성공 520 | 실패 1 | 건너뜀 0
[541/2755] 진행: 성공 540 | 실패 1 | 건너뜀 0
[561/2755] 진행: 성공 560 | 실패 1 | 건너뜀 0
[581/2755] 진행: 성공 580 | 실패 1 | 건너뜀 0
[601/2755] 진행: 성공 600 | 실패 1 | 건너뜀 0
[621/2755] 진행: 성공 620 | 실패 1 | 건너뜀 0
[641/2755] 진행: 성공 640 | 실패 1 | 건너뜀 0
[661/2755] 진행: 성공 660 | 실패 1 | 건너뜀 0
[681/2755] 진행: 성공 680 | 실패 1 | 건너뜀 0
[701/2755] 진행: 성공 700 | 실패 1 | 건너뜀 0
[721/2755] 진행: 성공 720 | 실패 1 | 건너뜀 0
[741/2755] 진행: 성공 740 | 실패 1 | 건너뜀 0
[761/2755] 진행: 성공 760 | 실패 1 | 건너뜀 0
[781/2755] 진행: 성공 780 | 실패 1 | 건너뜀 0
[801/2755] 진행: 성공 800 | 실패 1 | 건너뜀 0
[821/2755] 진행: 성공 820 | 실패 1 | 건너뜀 0
[841/2755] 진행: 성공 840 | 실패 1 | 건너뜀 0
[861/2755] 진행: 성공 860 | 실패 1 | 건너뜀 0
[881/2755] 진행: 성공 880 | 실패 1 | 건너뜀 0
[901/2755] 진행: 성공 900 | 실패 1 | 건너뜀 0
[921/2755] 진행: 성공 920 | 실패 1 | 건너뜀 0
[941/2755] 진행: 성공 940 | 실패 1 | 건너뜀 0
[961/2755] 진행: 성공 960 | 실패 1 | 건너뜀 0
[981/2755] 진행: 성공 980 | 실패 1 | 건너뜀 0
[1001/2755] 진행: 성공 1000 | 실패 1 | 건너뜀 0
[1021/2755] 진행: 성공 1020 | 실패 1 | 건너뜀 0
[1041/2755] 진행: 성공 1040 | 실패 1 | 건너뜀 0
[1061/2755] 진행: 성공 1060 | 실패 1 | 건너뜀 0
[1081/2755] 진행: 성공 1080 | 실패 1 | 건너뜀 0
[1101/2755] 진행: 성공 1100 | 실패 1 | 건너뜀 0
[1121/2755] 진행: 성공 1120 | 실패 1 | 건너뜀 0
[1141/2755] 진행: 성공 1140 | 실패 1 | 건너뜀 0
[1161/2755] 진행: 성공 1160 | 실패 1 | 건너뜀 0
[1181/2755] 진행: 성공 1180 | 실패 1 | 건너뜀 0
[1201/2755] 진행: 성공 1200 | 실패 1 | 건너뜀 0
[1221/2755] 진행: 성공 1220 | 실패 1 | 건너뜀 0
[1241/2755] 진행: 성공 1240 | 실패 1 | 건너뜀 0
[1261/2755] 진행: 성공 1260 | 실패 1 | 건너뜀 0
[1281/2755] 진행: 성공 1280 | 실패 1 | 건너뜀 0
[1301/2755] 진행: 성공 1300 | 실패 1 | 건너뜀 0
[1321/2755] 진행: 성공 1320 | 실패 1 | 건너뜀 0
[1341/2755] 진행: 성공 1340 | 실패 1 | 건너뜀 0
[1361/2755] 진행: 성공 1360 | 실패 1 | 건너뜀 0
[1381/2755] 진행: 성공 1380 | 실패 1 | 건너뜀 0
[1401/2755] 진행: 성공 1400 | 실패 1 | 건너뜀 0
[1421/2755] 진행: 성공 1420 | 실패 1 | 건너뜀 0
[1441/2755] 진행: 성공 1440 | 실패 1 | 건너뜀 0
[1461/2755] 진행: 성공 1460 | 실패 1 | 건너뜀 0
[1481/2755] 진행: 성공 1480 | 실패 1 | 건너뜀 0
[1501/2755] 진행: 성공 1500 | 실패 1 | 건너뜀 0
[1521/2755] 진행: 성공 1520 | 실패 1 | 건너뜀 0
[1541/2755] 진행: 성공 1540 | 실패 1 | 건너뜀 0
[1561/2755] 진행: 성공 1560 | 실패 1 | 건너뜀 0
[1581/2755] 진행: 성공 1580 | 실패 1 | 건너뜀 0
[1601/2755] 진행: 성공 1600 | 실패 1 | 건너뜀 0
[1621/2755] 진행: 성공 1620 | 실패 1 | 건너뜀 0
[1641/2755] 진행: 성공 1640 | 실패 1 | 건너뜀 0
[1661/2755] 진행: 성공 1660 | 실패 1 | 건너뜀 0
[1681/2755] 진행: 성공 1680 | 실패 1 | 건너뜀 0
[1701/2755] 진행: 성공 1700 | 실패 1 | 건너뜀 0
[1721/2755] 진행: 성공 1720 | 실패 1 | 건너뜀 0
[1741/2755] 진행: 성공 1740 | 실패 1 | 건너뜀 0
[1761/2755] 진행: 성공 1760 | 실패 1 | 건너뜀 0
[1781/2755] 진행: 성공 1780 | 실패 1 | 건너뜀 0
[1801/2755] 진행: 성공 1800 | 실패 1 | 건너뜀 0
[1821/2755] 진행: 성공 1820 | 실패 1 | 건너뜀 0
[1841/2755] 진행: 성공 1840 | 실패 1 | 건너뜀 0
[1861/2755] 진행: 성공 1860 | 실패 1 | 건너뜀 0
[1881/2755] 진행: 성공 1880 | 실패 1 | 건너뜀 0
[1901/2755] 진행: 성공 1900 | 실패 1 | 건너뜀 0
[1921/2755] 진행: 성공 1920 | 실패 1 | 건너뜀 0
[1941/2755] 진행: 성공 1940 | 실패 1 | 건너뜀 0
[1961/2755] 진행: 성공 1960 | 실패 1 | 건너뜀 0
[1981/2755] 진행: 성공 1980 | 실패 1 | 건너뜀 0
[2001/2755] 진행: 성공 2000 | 실패 1 | 건너뜀 0
[2021/2755] 진행: 성공 2020 | 실패 1 | 건너뜀 0
[2041/2755] 진행: 성공 2040 | 실패 1 | 건너뜀 0
[2061/2755] 진행: 성공 2060 | 실패 1 | 건너뜀 0
[2081/2755] 진행: 성공 2080 | 실패 1 | 건너뜀 0
[2101/2755] 진행: 성공 2100 | 실패 1 | 건너뜀 0
[2121/2755] 진행: 성공 2120 | 실패 1 | 건너뜀 0
[2141/2755] 진행: 성공 2140 | 실패 1 | 건너뜀 0
[2161/2755] 진행: 성공 2160 | 실패 1 | 건너뜀 0
[2181/2755] 진행: 성공 2180 | 실패 1 | 건너뜀 0
[2201/2755] 진행: 성공 2200 | 실패 1 | 건너뜀 0
[2221/2755] 진행: 성공 2220 | 실패 1 | 건너뜀 0
[2241/2755] 진행: 성공 2240 | 실패 1 | 건너뜀 0
[2261/2755] 진행: 성공 2260 | 실패 1 | 건너뜀 0
[2281/2755] 진행: 성공 2280 | 실패 1 | 건너뜀 0
[2301/2755] 진행: 성공 2300 | 실패 1 | 건너뜀 0
[2321/2755] 진행: 성공 2320 | 실패 1 | 건너뜀 0
[2341/2755] 진행: 성공 2340 | 실패 1 | 건너뜀 0
[2361/2755] 진행: 성공 2360 | 실패 1 | 건너뜀 0
[2381/2755] 진행: 성공 2380 | 실패 1 | 건너뜀 0
[2401/2755] 진행: 성공 2400 | 실패 1 | 건너뜀 0
[2421/2755] 진행: 성공 2420 | 실패 1 | 건너뜀 0
[2441/2755] 진행: 성공 2440 | 실패 1 | 건너뜀 0
[2461/2755] 진행: 성공 2460 | 실패 1 | 건너뜀 0
[2481/2755] 진행: 성공 2480 | 실패 1 | 건너뜀 0
[2483/2755] 실패 382/TX_38202_A531: ConnectionError: HTTPSConnectionPool(host='kosis.kr', port=443): Max retries exceeded with url: /openapi/statisticsData.do?method=getMeta&type=ITM&apiKey=ZTFiMTMzZDliNDQyYmRlMWI5MjJjMmUxNzgyODg3NGM%3D&orgId=382&tblId=TX_38202_A531&format=json (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x78a5b2f34380>: Failed to resolve 'kosis.kr' ([Errno -5] No address associated with hostname)"))
[2502/2755] 진행: 성공 2500 | 실패 2 | 건너뜀 0
[2522/2755] 진행: 성공 2520 | 실패 2 | 건너뜀 0
[2542/2755] 진행: 성공 2540 | 실패 2 | 건너뜀 0
[2562/2755] 진행: 성공 2560 | 실패 2 | 건너뜀 0
[2582/2755] 진행: 성공 2580 | 실패 2 | 건너뜀 0
[2602/2755] 진행: 성공 2600 | 실패 2 | 건너뜀 0
[2622/2755] 진행: 성공 2620 | 실패 2 | 건너뜀 0
[2642/2755] 진행: 성공 2640 | 실패 2 | 건너뜀 0
[2662/2755] 진행: 성공 2660 | 실패 2 | 건너뜀 0
[2682/2755] 진행: 성공 2680 | 실패 2 | 건너뜀 0
[2702/2755] 진행: 성공 2700 | 실패 2 | 건너뜀 0
[2722/2755] 진행: 성공 2720 | 실패 2 | 건너뜀 0
[2742/2755] 진행: 성공 2740 | 실패 2 | 건너뜀 0

완료: 성공 2753 | 실패 2 | 건너뜀(이미 완료) 0
저장: kosis_metadata_summary_enriched_tf.csv
meta-index 동시 저장: kosis_meta_index_tf.csv (build_kosis_meta_index.py 별도 실행 불필요)

In [15]:
import pandas as pd

df_meta_combined = pd.concat([
    pd.read_csv("kosis_meta_index_v2.csv"),      # 재정+도소매+소득소비+물가 (10065개)
    pd.read_csv("kosis_meta_index_tf.csv"),      # 무역+금융 (새로)
], ignore_index=True).drop_duplicates()
df_meta_combined.to_csv("kosis_meta_index_final.csv", index=False, encoding="utf-8-sig")

df_summary_combined = pd.concat([
    pd.read_csv("kosis_metadata_summary_enriched.csv"),
    pd.read_csv("kosis_metadata_summary_enriched_tf.csv"),
], ignore_index=True).drop_duplicates(subset=["ORG_ID","TBL_ID"])
df_summary_combined.to_csv("kosis_metadata_summary_enriched_final.csv", index=False, encoding="utf-8-sig")

print("meta:", len(df_meta_combined), "| summary:", len(df_summary_combined))

meta: 179746 | summary: 4811

In [17]:
!python embed_kosis_catalog_local.py \
    --catalog kosis_metadata_summary_enriched_final.csv \
    --output kosis_stat_catalog_embeddings_final.csv

[1/4811] OK 174/DT_163002_B001 (dim=1024)
[2/4811] OK 174/DT_163002_B002 (dim=1024)
[3/4811] OK 174/DT_163002_B0021 (dim=1024)
[4/4811] OK 174/DT_163002_B003 (dim=1024)
[5/4811] OK 174/DT_163002_B0031 (dim=1024)
[6/4811] OK 174/DT_163002_B004 (dim=1024)
[7/4811] OK 174/DT_163002_B005 (dim=1024)
[8/4811] OK 174/DT_163002_B006 (dim=1024)
[9/4811] OK 174/DT_163002_B007 (dim=1024)
[10/4811] OK 174/DT_163002_B0071 (dim=1024)
[11/4811] OK 174/DT_163002_B008 (dim=1024)
[12/4811] OK 174/DT_163002_B0081 (dim=1024)
[13/4811] OK 174/DT_163002_B009 (dim=1024)
[14/4811] OK 174/DT_163002_B010 (dim=1024)
[15/4811] OK 174/DT_163002_B011 (dim=1024)
[16/4811] OK 174/DT_163002_B012 (dim=1024)
[17/4811] OK 174/DT_163002_B013 (dim=1024)
[18/4811] OK 174/DT_163002_B014 (dim=1024)
[19/4811] OK 174/DT_163002_B015 (dim=1024)
[20/4811] OK 174/DT_163002_B016 (dim=1024)
[21/4811] OK 174/DT_163002_B017 (dim=1024)
[22/4811] OK 174/DT_163002_B018 (dim=1024)
[23/4811] OK 174/DT_163002_B019 (dim=1024)
[24/4811] OK 174/DT_163002_B021 (dim=1024)
[25/4811] OK 174/DT_163002_B022 (dim=1024)
[26/4811] OK 174/DT_163002_B0221 (dim=1024)
[27/4811] OK 174/DT_163002_B023 (dim=1024)
[28/4811] OK 174/DT_163002_A001 (dim=1024)
[29/4811] OK 174/DT_163002_A002 (dim=1024)
[30/4811] OK 174/DT_163002_A003 (dim=1024)
[31/4811] OK 174/DT_163002_A004 (dim=1024)
[32/4811] OK 174/DT_163002_A005 (dim=1024)
[33/4811] OK 174/DT_163002_A006 (dim=1024)
[34/4811] OK 174/DT_163002_A007 (dim=1024)
[35/4811] OK 174/DT_163002_A008 (dim=1024)
[36/4811] OK 174/DT_163002_A009 (dim=1024)
[37/4811] OK 174/DT_163002_A010 (dim=1024)
[38/4811] OK 174/DT_163002_A011 (dim=1024)
[39/4811] OK 174/DT_163002_A012 (dim=1024)
[40/4811] OK 174/DT_163002_A013 (dim=1024)
[41/4811] OK 174/DT_163002_A014 (dim=1024)
[42/4811] OK 174/DT_163002_A016 (dim=1024)
[43/4811] OK 174/DT_163002_A017 (dim=1024)
[44/4811] OK 174/DT_163002_A018 (dim=1024)
[45/4811] OK 174/DT_163002_A0181 (dim=1024)
[46/4811] OK 174/DT_163002_A019 (dim=1024)
[47/4811] OK 174/DT_163002_A020 (dim=1024)
[48/4811] OK 174/DT_163002_A021_1 (dim=1024)
[49/4811] OK 174/DT_163002_A021 (dim=1024)
[50/4811] OK 174/DT_163002_A022 (dim=1024)
[51/4811] OK 174/DT_163002_A023 (dim=1024)
[52/4811] OK 174/DT_163002_A024 (dim=1024)
[53/4811] OK 174/DT_163002_A025 (dim=1024)
[54/4811] OK 174/DT_163002_A026 (dim=1024)
[55/4811] OK 174/DT_163002_A027 (dim=1024)
[56/4811] OK 174/DT_163002_A028 (dim=1024)
[57/4811] OK 174/DT_163002_A029 (dim=1024)
[58/4811] OK 174/DT_163002_A030 (dim=1024)
[59/4811] OK 174/DT_163002_A031 (dim=1024)
[60/4811] OK 174/DT_163002_A032 (dim=1024)
[61/4811] OK 174/DT_163002_A033 (dim=1024)
[62/4811] OK 174/DT_163002_A034 (dim=1024)
[63/4811] OK 174/DT_163002_A035 (dim=1024)
[64/4811] OK 174/DT_163002_A0351 (dim=1024)
[65/4811] OK 109/TX_10905_A002 (dim=1024)
[66/4811] OK 109/TX_10905_A001 (dim=1024)
[67/4811] OK 109/TX_10905_A000 (dim=1024)
[68/4811] OK 103/TX_10303_A000 (dim=1024)
[69/4811] OK 103/TX_10303_A001 (dim=1024)
[70/4811] OK 103/TX_10303_A002 (dim=1024)
[71/4811] OK 101/DT_FR0001 (dim=1024)
[72/4811] OK 101/DT_FR0002 (dim=1024)
[73/4811] OK 101/DT_FR0003 (dim=1024)
[74/4811] OK 101/DT_FR0004 (dim=1024)
[75/4811] OK 101/DT_FR0006 (dim=1024)
[76/4811] OK 101/DT_FR0001N (dim=1024)
[77/4811] OK 101/DT_FR0005 (dim=1024)
[78/4811] OK 101/DT_FR0007 (dim=1024)
[79/4811] OK 113/DT_113_STBL_1024737 (dim=1024)
[80/4811] OK 113/DT_113_STBL_1024741 (dim=1024)
[81/4811] OK 113/DT_113_STBL_1024738 (dim=1024)
[82/4811] OK 113/DT_113_STBL_1024742 (dim=1024)
[83/4811] OK 113/DT_113_STBL_1020629 (dim=1024)
[84/4811] OK 113/DT_113_STBL_1024662 (dim=1024)
[85/4811] OK 113/DT_113_STBL_1020641 (dim=1024)
[86/4811] OK 113/DT_113_STBL_1020642 (dim=1024)
[87/4811] OK 113/DT_113_STBL_1020643 (dim=1024)
[88/4811] OK 113/DT_113_STBL_1020649 (dim=1024)
[89/4811] OK 113/DT_113_STBL_1020650 (dim=1024)
[90/4811] OK 113/DT_113_STBL_1020651 (dim=1024)
[91/4811] OK 113/DT_113_STBL_1020652 (dim=1024)
[92/4811] OK 113/DT_113_STBL_1020644 (dim=1024)
[93/4811] OK 113/DT_113_STBL_1020645 (dim=1024)
[94/4811] OK 113/DT_113_STBL_1020646 (dim=1024)
[95/4811] OK 113/DT_113_STBL_1020647 (dim=1024)
[96/4811] OK 113/DT_113_STBL_1020675 (dim=1024)
[97/4811] OK 113/DT_113_STBL_1020677 (dim=1024)
[98/4811] OK 113/DT_113_STBL_1020654 (dim=1024)
[99/4811] OK 113/DT_113_STBL_1020655 (dim=1024)
[100/4811] OK 113/DT_113_STBL_1024666 (dim=1024)
[101/4811] OK 113/DT_113_STBL_1020656 (dim=1024)
[102/4811] OK 113/DT_113_STBL_1020662 (dim=1024)
[103/4811] OK 113/DT_113_STBL_1020663 (dim=1024)
[104/4811] OK 113/DT_113_STBL_1020664 (dim=1024)
[105/4811] OK 113/DT_113_STBL_1020665 (dim=1024)
[106/4811] OK 113/DT_113_STBL_1020657 (dim=1024)
[107/4811] OK 113/DT_113_STBL_1020658 (dim=1024)
[108/4811] OK 113/DT_113_STBL_1020660 (dim=1024)
[109/4811] OK 113/DT_113_STBL_1020661 (dim=1024)
[110/4811] OK 113/DT_113_STBL_1021512 (dim=1024)
[111/4811] OK 113/DT_113_STBL_1018034 (dim=1024)
[112/4811] OK 113/DT_113_STBL_1018055 (dim=1024)
[113/4811] OK 113/DT_113_STBL_1018051 (dim=1024)
[114/4811] OK 113/DT_113_STBL_1023560 (dim=1024)
[115/4811] OK 113/DT_113_STBL_1023551 (dim=1024)
[116/4811] OK 113/DT_113_STBL_1023559 (dim=1024)
[117/4811] OK 113/DT_113_STBL_1023561 (dim=1024)
[118/4811] OK 113/DT_113_STBL_1024793 (dim=1024)
[119/4811] OK 113/DT_113_STBL_1020390 (dim=1024)
[120/4811] OK 113/DT_113_STBL_1024795 (dim=1024)
[121/4811] OK 113/DT_113_STBL_1020393 (dim=1024)
[122/4811] OK 113/DT_113_STBL_1020374 (dim=1024)
[123/4811] OK 113/DT_113_STBL_1020373 (dim=1024)
[124/4811] OK 113/DT_113_STBL_1020372 (dim=1024)
[125/4811] OK 113/DT_113_STBL_1017620 (dim=1024)
[126/4811] OK 113/DT_113_STBL_1017612 (dim=1024)
[127/4811] OK 113/DT_113_STBL_1023555 (dim=1024)
[128/4811] OK 113/DT_113_STBL_1023553 (dim=1024)
[129/4811] OK 113/DT_113_STBL_1020172 (dim=1024)
[130/4811] OK 113/DT_113_STBL_1020179 (dim=1024)
[131/4811] OK 113/DT_113_STBL_1017627 (dim=1024)
[132/4811] OK 113/DT_113_STBL_1024671 (dim=1024)
[133/4811] OK 113/DT_113_STBL_1024672 (dim=1024)
[134/4811] OK 113/DT_113_STBL_1024695 (dim=1024)
[135/4811] OK 113/DT_113_STBL_1024699 (dim=1024)
[136/4811] OK 113/DT_113_STBL_1024696 (dim=1024)
[137/4811] OK 113/DT_113_STBL_1024700 (dim=1024)
[138/4811] OK 113/DT_113_STBL_1024673 (dim=1024)
[139/4811] OK 113/DT_113_STBL_1023732 (dim=1024)
[140/4811] OK 113/DT_113_STBL_1023733 (dim=1024)
[141/4811] OK 113/DT_113_STBL_1023729 (dim=1024)
[142/4811] OK 113/DT_113_STBL_1023731 (dim=1024)
[143/4811] OK 113/DT_113_STBL_1023725 (dim=1024)
[144/4811] OK 113/DT_113_STBL_1020448 (dim=1024)
[145/4811] OK 113/DT_113_STBL_1020203 (dim=1024)
[146/4811] OK 113/DT_113_STBL_1020486 (dim=1024)
[147/4811] OK 113/DT_113_STBL_1023726 (dim=1024)
[148/4811] OK 113/DT_113_STBL_1024819 (dim=1024)
[149/4811] OK 113/DT_113_STBL_1024820 (dim=1024)
[150/4811] OK 113/DT_113_STBL_1020451 (dim=1024)
[151/4811] OK 113/DT_113_STBL_1020453 (dim=1024)
[152/4811] OK 113/DT_113_STBL_1023723 (dim=1024)
[153/4811] OK 113/DT_113_STBL_1020454 (dim=1024)
[154/4811] OK 113/DT_113_STBL_1020447 (dim=1024)
[155/4811] OK 113/DT_113_STBL_1020186 (dim=1024)
[156/4811] OK 113/DT_113_STBL_1020498 (dim=1024)
[157/4811] OK 113/DT_113_STBL_1020499 (dim=1024)
[158/4811] OK 113/DT_113_STBL_1020493 (dim=1024)
[159/4811] OK 113/DT_113_STBL_1020496 (dim=1024)
[160/4811] OK 113/DT_113_STBL_1020494 (dim=1024)
[161/4811] OK 113/DT_113_STBL_1020495 (dim=1024)
[162/4811] OK 113/DT_113_STBL_1020196 (dim=1024)
[163/4811] OK 113/DT_113_STBL_1016278 (dim=1024)
[164/4811] OK 113/DT_113_STBL_1023728 (dim=1024)
[165/4811] OK 113/DT_113_STBL_1020534 (dim=1024)
[166/4811] OK 113/DT_113_STBL_1020535 (dim=1024)
[167/4811] OK 113/DT_113_STBL_1016448 (dim=1024)
[168/4811] OK 113/DT_113_STBL_1024859 (dim=1024)
[169/4811] OK 113/DT_113_STBL_1017416 (dim=1024)
[170/4811] OK 113/DT_113_STBL_1020545 (dim=1024)
[171/4811] OK 113/DT_113_STBL_1016540 (dim=1024)
[172/4811] OK 113/DT_113_STBL_1020569 (dim=1024)
[173/4811] OK 113/DT_113_STBL_1017753 (dim=1024)
[174/4811] OK 113/DT_113_STBL_1016579 (dim=1024)
[175/4811] OK 113/DT_113_STBL_1020571 (dim=1024)
[176/4811] OK 113/DT_113_STBL_1020549 (dim=1024)
[177/4811] OK 113/DT_113_STBL_1020548 (dim=1024)
[178/4811] OK 113/DT_113_STBL_1020550 (dim=1024)
[179/4811] OK 113/DT_113_STBL_1024610 (dim=1024)
[180/4811] OK 113/DT_113_STBL_1024829 (dim=1024)
[181/4811] OK 113/DT_113_STBL_1019692 (dim=1024)
[182/4811] OK 113/DT_113_STBL_1020573 (dim=1024)
[183/4811] OK 113/DT_113_STBL_1017760 (dim=1024)
[184/4811] OK 113/DT_113_STBL_1020561 (dim=1024)
[185/4811] OK 113/DT_113_STBL_1020557 (dim=1024)
[186/4811] OK 113/DT_113_STBL_1020555 (dim=1024)
[187/4811] OK 113/DT_113_STBL_1020559 (dim=1024)
[188/4811] OK 113/DT_113_STBL_1020558 (dim=1024)
[189/4811] OK 113/DT_113_STBL_1016465 (dim=1024)
[190/4811] OK 113/DT_113_STBL_1024646 (dim=1024)
[191/4811] OK 113/DT_113_STBL_1024643 (dim=1024)
[192/4811] OK 113/DT_113_STBL_1024650 (dim=1024)
[193/4811] OK 113/DT_113_STBL_1024649 (dim=1024)
[194/4811] OK 113/DT_113_STBL_1024648 (dim=1024)
[195/4811] OK 113/DT_113_STBL_1024616 (dim=1024)
[196/4811] OK 113/DT_113_STBL_1024618 (dim=1024)
[197/4811] OK 113/DT_113_STBL_1024653 (dim=1024)
[198/4811] OK 113/DT_113_STBL_1024636 (dim=1024)
[199/4811] OK 113/DT_113_STBL_1024639 (dim=1024)
[200/4811] OK 113/DT_113_STBL_1024621 (dim=1024)
[201/4811] OK 113/DT_113_STBL_1024645 (dim=1024)
[202/4811] OK 113/DT_113_STBL_1024642 (dim=1024)
[203/4811] OK 113/DT_113_STBL_1024641 (dim=1024)
[204/4811] OK 113/DT_113_STBL_1024619 (dim=1024)
[205/4811] OK 113/DT_113_STBL_1024632 (dim=1024)
[206/4811] OK 113/DT_113_STBL_1024633 (dim=1024)
[207/4811] OK 113/DT_113_STBL_1024640 (dim=1024)
[208/4811] OK 113/DT_113_STBL_1024651 (dim=1024)
[209/4811] OK 113/DT_113_STBL_1024644 (dim=1024)
[210/4811] OK 113/DT_113_STBL_1024617 (dim=1024)
[211/4811] OK 113/DT_113_STBL_1017871 (dim=1024)
[212/4811] OK 113/DT_113_STBL_1016611 (dim=1024)
[213/4811] OK 113/DT_113_STBL_1024878 (dim=1024)
[214/4811] OK 113/DT_113_STBL_1017868 (dim=1024)
[215/4811] OK 113/DT_113_STBL_1016627 (dim=1024)
[216/4811] OK 113/DT_113_STBL_1016742 (dim=1024)
[217/4811] OK 113/DT_113_STBL_1020585 (dim=1024)
[218/4811] OK 113/DT_113_STBL_1020584 (dim=1024)
[219/4811] OK 113/DT_113_STBL_1024877 (dim=1024)
[220/4811] OK 113/DT_113_STBL_1024876 (dim=1024)
[221/4811] OK 113/DT_113_STBL_1024874 (dim=1024)
[222/4811] OK 113/DT_113_STBL_1024652 (dim=1024)
[223/4811] OK 113/DT_113_STBL_1024882 (dim=1024)
[224/4811] OK 113/DT_113_STBL_1025420 (dim=1024)
[225/4811] OK 113/DT_113_STBL_1017794 (dim=1024)
[226/4811] OK 113/DT_113_STBL_1017792 (dim=1024)
[227/4811] OK 113/DT_113_STBL_1017791 (dim=1024)
[228/4811] OK 113/DT_113_STBL_1023470 (dim=1024)
[229/4811] OK 113/DT_113_STBL_1020366 (dim=1024)
[230/4811] OK 113/DT_113_STBL_1023541 (dim=1024)
[231/4811] OK 113/DT_113_STBL_1015244 (dim=1024)
[232/4811] OK 113/DT_113_STBL_1017551 (dim=1024)
[233/4811] OK 113/DT_113_STBL_1015503 (dim=1024)
[234/4811] OK 113/DT_113_STBL_1015418 (dim=1024)
[235/4811] OK 113/DT_113_STBL_1020357 (dim=1024)
[236/4811] OK 113/DT_113_STBL_1020356 (dim=1024)
[237/4811] OK 113/DT_113_STBL_1020362 (dim=1024)
[238/4811] OK 113/DT_113_STBL_1020354 (dim=1024)
[239/4811] OK 113/DT_113_STBL_1020360 (dim=1024)
[240/4811] OK 113/DT_113_STBL_1023476 (dim=1024)
[241/4811] OK 113/DT_113_STBL_1020363 (dim=1024)
[242/4811] OK 113/DT_113_STBL_1020355 (dim=1024)
[243/4811] OK 113/DT_113_STBL_1020371 (dim=1024)
[244/4811] OK 113/DT_113_STBL_1023544 (dim=1024)
[245/4811] OK 113/DT_113_STBL_1020367 (dim=1024)
[246/4811] OK 113/DT_113_STBL_1023413 (dim=1024)
[247/4811] OK 113/DT_113_STBL_1024799 (dim=1024)
[248/4811] OK 113/DT_113_STBL_1024798 (dim=1024)
[249/4811] OK 113/DT_113_STBL_1024803 (dim=1024)
[250/4811] OK 113/DT_113_STBL_1024802 (dim=1024)
[251/4811] OK 113/DT_113_STBL_1024753 (dim=1024)
[252/4811] OK 113/DT_113_STBL_1017636 (dim=1024)
[253/4811] OK 113/DT_113_STBL_1024812 (dim=1024)
[254/4811] OK 113/DT_113_STBL_1020435 (dim=1024)
[255/4811] OK 113/DT_113_STBL_1020410 (dim=1024)
[256/4811] OK 113/DT_113_STBL_1020409 (dim=1024)
[257/4811] OK 113/DT_113_STBL_1020421 (dim=1024)
[258/4811] OK 113/DT_113_STBL_1020407 (dim=1024)
[259/4811] OK 113/DT_113_STBL_1024814 (dim=1024)
[260/4811] OK 113/DT_113_STBL_1020440 (dim=1024)
[261/4811] OK 113/DT_113_STBL_1020422 (dim=1024)
[262/4811] OK 113/DT_113_STBL_1020408 (dim=1024)
[263/4811] OK 113/DT_113_STBL_1020423 (dim=1024)
[264/4811] OK 113/DT_113_STBL_1020420 (dim=1024)
[265/4811] OK 113/DT_113_STBL_1015922 (dim=1024)
[266/4811] OK 113/DT_113_STBL_1020164 (dim=1024)
[267/4811] OK 113/DT_113_STBL_1023563 (dim=1024)
[268/4811] OK 113/DT_113_STBL_1017899 (dim=1024)
[269/4811] OK 113/DT_113_STBL_1016747 (dim=1024)
[270/4811] OK 113/DT_113_STBL_1021542 (dim=1024)
[271/4811] OK 113/DT_113_STBL_1024872 (dim=1024)
[272/4811] OK 113/DT_113_STBL_1020500 (dim=1024)
[273/4811] OK 113/DT_113_STBL_1023492 (dim=1024)
[274/4811] OK 113/DT_113_STBL_1020518 (dim=1024)
[275/4811] OK 113/DT_113_STBL_1020523 (dim=1024)
[276/4811] OK 113/DT_113_STBL_1016349 (dim=1024)
[277/4811] OK 113/DT_113_STBL_1020519 (dim=1024)
[278/4811] OK 113/DT_113_STBL_1024836 (dim=1024)
[279/4811] OK 113/DT_113_STBL_1023497 (dim=1024)
[280/4811] OK 113/DT_113_STBL_1024855 (dim=1024)
[281/4811] OK 113/DT_113_STBL_1017712 (dim=1024)
[282/4811] OK 113/DT_113_STBL_1020521 (dim=1024)
[283/4811] OK 113/DT_113_STBL_1020516 (dim=1024)
[284/4811] OK 113/DT_113_STBL_1020522 (dim=1024)
[285/4811] OK 113/DT_113_STBL_1020526 (dim=1024)
[286/4811] OK 113/DT_113_STBL_1020504 (dim=1024)
[287/4811] OK 113/DT_113_STBL_1020506 (dim=1024)
[288/4811] OK 113/DT_113_STBL_1020503 (dim=1024)
[289/4811] OK 113/DT_113_STBL_1020502 (dim=1024)
[290/4811] OK 113/DT_113_STBL_1020513 (dim=1024)
[291/4811] OK 113/DT_113_STBL_1018103 (dim=1024)
[292/4811] OK 113/DT_113_STBL_1023510 (dim=1024)
[293/4811] OK 113/DT_113_STBL_1023509 (dim=1024)
[294/4811] OK 113/DT_113_STBL_1024716 (dim=1024)
[295/4811] OK 113/DT_113_STBL_1024717 (dim=1024)
[296/4811] OK 113/DT_113_STBL_1025036 (dim=1024)
[297/4811] OK 113/DT_113_STBL_1025732 (dim=1024)
[298/4811] OK 113/DT_113_STBL_1025039 (dim=1024)
[299/4811] OK 113/DT_113_STBL_1024718 (dim=1024)
[300/4811] OK 113/DT_113_STBL_1025733 (dim=1024)
[301/4811] OK 113/DT_113_STBL_1024725 (dim=1024)
[302/4811] OK 113/DT_113_STBL_1024749 (dim=1024)
[303/4811] OK 113/DT_113_STBL_1024750 (dim=1024)
[304/4811] OK 113/DT_113_STBL_1024726 (dim=1024)
[305/4811] OK 113/DT_113_STBL_1024727 (dim=1024)
[306/4811] OK 113/DT_113_STBL_1024728 (dim=1024)
[307/4811] OK 113/DT_113_STBL_1024731 (dim=1024)
[308/4811] OK 113/DT_113_STBL_1025734 (dim=1024)
[309/4811] OK 113/DT_113_STBL_1024736 (dim=1024)
[310/4811] OK 113/DT_113_STBL_1031294 (dim=1024)
[311/4811] OK 113/DT_113_STBL_1031295 (dim=1024)
[312/4811] OK 113/DT_113_STBL_1024739 (dim=1024)
[313/4811] OK 113/DT_113_STBL_1024740 (dim=1024)
[314/4811] OK 113/DT_113_STBL_1024743 (dim=1024)
[315/4811] OK 113/DT_113_STBL_1024744 (dim=1024)
[316/4811] OK 113/DT_113_STBL_1027320 (dim=1024)
[317/4811] OK 113/DT_113_STBL_1027321 (dim=1024)
[318/4811] OK 113/DT_113_STBL_1024747 (dim=1024)
[319/4811] OK 113/DT_113_STBL_1024748 (dim=1024)
[320/4811] OK 113/DT_113_STBL_1025730 (dim=1024)
[321/4811] OK 113/DT_113_STBL_1025037 (dim=1024)
[322/4811] OK 113/DT_113_STBL_1025038 (dim=1024)
[323/4811] OK 113/DT_113_STBL_1024732 (dim=1024)
[324/4811] OK 113/DT_113_STBL_1024733 (dim=1024)
[325/4811] OK 113/DT_113_STBL_1024721 (dim=1024)
[326/4811] OK 113/DT_113_STBL_1024722 (dim=1024)
[327/4811] OK 113/DT_113_STBL_1024723 (dim=1024)
[328/4811] OK 113/DT_113_STBL_1024724 (dim=1024)
[329/4811] OK 113/DT_113_STBL_1024720 (dim=1024)
[330/4811] OK 113/DT_113_STBL_1024719 (dim=1024)
[331/4811] OK 113/DT_113_STBL_1024729 (dim=1024)
[332/4811] OK 113/DT_113_STBL_1024730 (dim=1024)
[333/4811] OK 113/DT_113_STBL_1024734 (dim=1024)
[334/4811] OK 113/DT_113_STBL_1024735 (dim=1024)
[335/4811] OK 113/DT_113_STBL_1024746 (dim=1024)
[336/4811] OK 113/DT_113_STBL_1024745 (dim=1024)
[337/4811] OK 113/DT_113_STBL_1024608 (dim=1024)
[338/4811] OK 113/DT_113_STBL_1027238 (dim=1024)
[339/4811] OK 113/DT_113_STBL_1025099 (dim=1024)
[340/4811] OK 113/DT_113_STBL_1027241 (dim=1024)
[341/4811] OK 113/DT_113_STBL_1027246 (dim=1024)
[342/4811] OK 113/DT_113_STBL_1027253 (dim=1024)
[343/4811] OK 113/DT_113_STBL_1021535 (dim=1024)
[344/4811] OK 113/DT_113_STBL_1020577 (dim=1024)
[345/4811] OK 113/DT_113_STBL_1020578 (dim=1024)
[346/4811] OK 113/DT_113_STBL_1017585 (dim=1024)
[347/4811] OK 113/DT_113_STBL_1020562 (dim=1024)
[348/4811] OK 113/DT_113_STBL_1020563 (dim=1024)
[349/4811] OK 113/DT_113_STBL_1016527 (dim=1024)
[350/4811] OK 113/DT_113_STBL_1021532 (dim=1024)
[351/4811] OK 113/DT_113_STBL_1021533 (dim=1024)
[352/4811] OK 113/DT_113_STBL_1031284 (dim=1024)
[353/4811] OK 113/DT_113_STBL_1031285 (dim=1024)
[354/4811] OK 113/DT_113_STBL_1020184 (dim=1024)
[355/4811] OK 113/DT_113_STBL_1016597 (dim=1024)
[356/4811] OK 113/DT_113_STBL_1027262 (dim=1024)
[357/4811] OK 113/DT_113_STBL_1020574 (dim=1024)
[358/4811] OK 113/DT_113_STBL_1027267 (dim=1024)
[359/4811] OK 113/DT_113_STBL_1020575 (dim=1024)
[360/4811] OK 113/DT_113_STBL_1025674 (dim=1024)
[361/4811] OK 113/DT_113_STBL_1025100 (dim=1024)
[362/4811] OK 113/DT_113_STBL_1025675 (dim=1024)
[363/4811] OK 113/DT_113_STBL_1025101 (dim=1024)
[364/4811] OK 113/DT_113_STBL_1025677 (dim=1024)
[365/4811] OK 113/DT_113_STBL_1025102 (dim=1024)
[366/4811] OK 113/DT_113_STBL_1016501 (dim=1024)
[367/4811] OK 113/DT_113_STBL_1020552 (dim=1024)
[368/4811] OK 113/DT_113_STBL_1018622 (dim=1024)
[369/4811] OK 113/DT_113_STBL_1020553 (dim=1024)
[370/4811] OK 113/DT_113_STBL_1020187 (dim=1024)
[371/4811] OK 113/DT_113_STBL_1020551 (dim=1024)
[372/4811] OK 113/DT_113_STBL_1021534 (dim=1024)
[373/4811] OK 113/DT_113_STBL_1017774 (dim=1024)
[374/4811] OK 113/DT_113_STBL_1024611 (dim=1024)
[375/4811] OK 113/DT_113_STBL_1020565 (dim=1024)
[376/4811] OK 113/DT_113_STBL_1020564 (dim=1024)
[377/4811] OK 113/DT_113_STBL_1016534 (dim=1024)
[378/4811] OK 113/DT_113_STBL_1020566 (dim=1024)
[379/4811] OK 113/DT_113_STBL_1016536 (dim=1024)
[380/4811] OK 113/DT_113_STBL_1020567 (dim=1024)
[381/4811] OK 113/DT_113_STBL_1025113 (dim=1024)
[382/4811] OK 113/DT_113_STBL_1016601 (dim=1024)
[383/4811] OK 113/DT_113_STBL_1016602 (dim=1024)
[384/4811] OK 113/DT_113_STBL_1023512 (dim=1024)
[385/4811] OK 113/DT_113_STBL_1027323 (dim=1024)
[386/4811] OK 113/DT_113_STBL_1027325 (dim=1024)
[387/4811] OK 113/DT_113_STBL_1027211 (dim=1024)
[388/4811] OK 113/DT_113_STBL_1027214 (dim=1024)
[389/4811] OK 113/DT_113_STBL_1025665 (dim=1024)
[390/4811] OK 113/DT_113_STBL_1017724 (dim=1024)
[391/4811] OK 113/DT_113_STBL_1031279 (dim=1024)
[392/4811] OK 113/DT_113_STBL_1020539 (dim=1024)
[393/4811] OK 113/DT_113_STBL_1020540 (dim=1024)
[394/4811] OK 113/DT_113_STBL_1027226 (dim=1024)
[395/4811] OK 113/DT_113_STBL_1027227 (dim=1024)
[396/4811] OK 113/DT_113_STBL_1031280 (dim=1024)
[397/4811] OK 113/DT_113_STBL_1031281 (dim=1024)
[398/4811] OK 113/DT_113_STBL_1027230 (dim=1024)
[399/4811] OK 113/DT_113_STBL_1027231 (dim=1024)
[400/4811] OK 113/DT_113_STBL_1031728 (dim=1024)
[401/4811] OK 113/DT_113_STBL_1031727 (dim=1024)
[402/4811] OK 113/DT_113_STBL_1027234 (dim=1024)
[403/4811] OK 113/DT_113_STBL_1027235 (dim=1024)
[404/4811] OK 113/DT_113_STBL_1025673 (dim=1024)
[405/4811] OK 113/DT_113_STBL_1025666 (dim=1024)
[406/4811] OK 113/DT_113_STBL_1025659 (dim=1024)
[407/4811] OK 113/DT_113_STBL_1025660 (dim=1024)
[408/4811] OK 113/DT_113_STBL_1025661 (dim=1024)
[409/4811] OK 113/DT_113_STBL_1025663 (dim=1024)
[410/4811] OK 113/DT_113_STBL_1025082 (dim=1024)
[411/4811] OK 113/DT_113_STBL_1025664 (dim=1024)
[412/4811] OK 113/DT_113_STBL_1020536 (dim=1024)
[413/4811] OK 113/DT_113_STBL_1016358 (dim=1024)
[414/4811] OK 113/DT_113_STBL_1020537 (dim=1024)
[415/4811] OK 113/DT_113_STBL_1016409 (dim=1024)
[416/4811] OK 113/DT_113_STBL_1021523 (dim=1024)
[417/4811] OK 113/DT_113_STBL_1023523 (dim=1024)
[418/4811] OK 113/DT_113_STBL_1023521 (dim=1024)
[419/4811] OK 113/DT_113_STBL_1023515 (dim=1024)

In [22]:
!python search_kosis_catalog_local.py \
    --claims kosis_ready_plus_improvable.csv \
    --catalog-embeddings kosis_stat_catalog_embeddings_final.csv \
    --output kosis_table_candidates_final.csv \
    --top-k 3

카탈로그 4811개 테이블 로드 완료

생성: kosis_table_candidates_final.csv
claim 수: 142 | 1순위 후보 READY: 0 | 1순위 후보 NEEDS_CONFIRMATION: 142 | 후보 테이블 없음: 0

In [23]:
import pandas as pd
df_candidates = pd.read_csv("kosis_table_candidates_final.csv")
rank1 = df_candidates[df_candidates["candidate_rank"] == 1].copy()
rank1["cosine_distance"] = rank1["match_reason"].str.extract(r"cosine_distance=([\d.]+)").astype(float)

cols = ["metric_domain", "indicator", "tbl_nm", "cosine_distance"]
for domain in rank1["metric_domain"].unique():
    print(f"=== {domain} ===")
    print(rank1[rank1["metric_domain"] == domain][cols].head(3).to_string(index=False))

=== 소매·소비 ===
metric_domain  indicator         tbl_nm  cosine_distance
        소매·소비 설선물 매출 증가율 백화점 매출 동향(품목별)           0.3861
        소매·소비 설선물 매출 증가율 백화점 매출 동향(품목별)           0.3967
        소매·소비 설선물 매출 증가율 백화점 매출 동향(품목별)           0.3710
=== 재정·조세 ===
metric_domain indicator         tbl_nm  cosine_distance
        재정·조세     경제성장률    경기전망지수(가동율)           0.3752
        재정·조세  가계 여유 자금     가계대출 잔액 비중           0.3586
        재정·조세 순자금 운용 규모 금융자산 운용 비중(평균)           0.3855
=== 금융·금리 ===
metric_domain  indicator       tbl_nm  cosine_distance
        금융·금리 국채 10년물 금리 10년국채선물 거래실적           0.3872
        금융·금리       영업이익      영업이익 현황           0.3533
        금융·금리 영업이익 증가 배수 코스닥 상장사 수익현황           0.3965
=== 무역 ===
metric_domain  indicator             tbl_nm  cosine_distance
           무역  수입차 판매 대수       대차거래 현황 ; 채권           0.4149
           무역  수입차 판매 대수       대차거래 현황 ; 채권           0.3575
           무역 수입차 판매 증감률 음악산업 : 수출 및 수입액 현황           0.3857
=== 소득·임금 ===
metric_domain indicator              tbl_nm  cosine_distance
        소득·임금      가계소득 월평균 가구 소득(3차 소비자조사)           0.2983
=== 인구 ===
metric_domain indicator                tbl_nm  cosine_distance
           인구       출산율 출판산업 주요 국가·대륙별 수입액 현황           0.4849
           인구     관광객 수   해외 참관객 규모별 참관객 수 현황           0.4204
           인구 감소한 관광객 수   해외 참관객 규모별 참관객 수 현황           0.4429
=== 보건·복지 ===
metric_domain indicator       tbl_nm  cosine_distance
        보건·복지   자원봉사자 수 종사자 수별 사업체 수           0.4291
=== 물가 ===
metric_domain indicator              tbl_nm  cosine_distance
           물가   배추 소매가격 식재료 가격정보 획득방법(중복응답)           0.4882
           물가 배추 가격 상승률 식재료 가격정보 획득방법(중복응답)           0.4772
           물가 배추 가격 상승률 식재료 가격정보 획득방법(중복응답)           0.4772

In [27]:
import pandas as pd
df = pd.read_csv("kosis_metadata_summary_enriched_final.csv")
price_tables = df[df["category_path"].str.contains("물가", na=False)]
print(len(price_tables), "개 물가 표")
print(price_tables["TBL_NM"].tolist())

0 개 물가 표
[]

In [29]:
import pandas as pd
import os

for f in ["kosis_full_catalog_tf.csv", "kosis_metadata_summary_enriched_tf.csv", "kosis_meta_index_tf.csv"]:
    if os.path.exists(f):
        print(f, "->", len(pd.read_csv(f)), "행")
    else:
        print(f, "-> 파일 없음")

kosis_full_catalog_tf.csv -> 2755 행
kosis_metadata_summary_enriched_tf.csv -> 2753 행
kosis_meta_index_tf.csv -> 179746 행

In [25]:
!python kosis_validate_mapping_candidates.py \
    --input kosis_table_candidates_final.csv \
    --meta-index kosis_meta_index_final.csv \
    --output kosis_validated_final.csv \
    --max-combinations 20 --limit 0

candidate_rows=426 max_combinations_per_row=20 estimated_api_calls<=8520
validated_rows=426 output=kosis_validated_final.csv

In [26]:
df_validated = pd.read_csv("kosis_validated_final.csv")
print(df_validated.groupby("metric_domain")["mapping_status"].value_counts())

metric_domain  mapping_status
금융·금리          MAPPING_FAILED         39
               NOT_EVALUATED          20
               NEEDS_CONFIRMATION      1
무역             MAPPING_FAILED         83
               NOT_EVALUATED          48
               NEEDS_CONFIRMATION     13
물가             MAPPING_FAILED         10
               NOT_EVALUATED           6
               NEEDS_CONFIRMATION      2
보건·복지          MAPPING_FAILED          2
               NOT_EVALUATED           1
소득·임금          MAPPING_FAILED          2
               NOT_EVALUATED           1
소매·소비          MAPPING_FAILED        108
               NOT_EVALUATED          55
               NEEDS_CONFIRMATION      2
인구             MAPPING_FAILED          8
               NOT_EVALUATED           4
재정·조세          MAPPING_FAILED         12
               NOT_EVALUATED           7
               NEEDS_CONFIRMATION      2
Name: count, dtype: int64

In [30]:
!python enrich_kosis_catalog_meta.py \
      --input kosis_full_catalog_tf.csv \
      --output kosis_metadata_summary_enriched_tf.csv \
      --meta-index-output kosis_meta_index_tf.csv

이어받기: 2753개 표는 이미 완료되어 건너뜁니다.
[1/2] 실패 301/DT_105Y001: JSONDecodeError: Invalid \escape: line 1 column 3211 (char 3210)

완료: 성공 1 | 실패 1 | 건너뜀(이미 완료) 0
저장: kosis_metadata_summary_enriched_tf.csv
meta-index 동시 저장: kosis_meta_index_tf.csv (build_kosis_meta_index.py 별도 실행 불필요)

In [31]:
!python crawl_kosis_catalog.py --output kosis_full_catalog_tf.csv \
      --top-category-keywords "무역ㆍ국제수지,금융" --max-tables 300

크롤링 시작: vw_cd=MT_ZTITLE, max_depth=무제한, top_category_keywords=['무역ㆍ국제수지', '금융'], max_tables=300
진행: 카테고리 호출 20개 완료, 지금까지 표 102개, 대기 중인 카테고리 15개

중단됨 - 지금까지 모은 표 138개는 kosis_full_catalog_tf.csv 에 저장합니다.
중단됨. 그동안 저장된 kosis_full_catalog_tf.csv 을 그대로 쓰시면 됩니다.
이어서 더 모으고 싶으면 --resume 옵션으로 같은 --output 을 다시 실행하세요 (이미 모은 표는 중복 없이, 카테고리는 처음부터 다시 훑지만 표 자체는 안 겹칩니다).

In [32]:
import pandas as pd

df_meta_combined = pd.concat([
    pd.read_csv("kosis_meta_index_v2.csv"),   # 재정+도소매+소득소비+물가 (10065개)
    pd.read_csv("kosis_meta_index_tf.csv"),   # 무역+금융 (2754개)
], ignore_index=True).drop_duplicates()
df_meta_combined.to_csv("kosis_meta_index_final.csv", index=False, encoding="utf-8-sig")

df_summary_combined = pd.concat([
    pd.read_csv("kosis_metadata_summary_enriched.csv"),
    pd.read_csv("kosis_metadata_summary_enriched_tf.csv"),
], ignore_index=True).drop_duplicates(subset=["ORG_ID", "TBL_ID"])
df_summary_combined.to_csv("kosis_metadata_summary_enriched_final.csv", index=False, encoding="utf-8-sig")

print("meta:", len(df_meta_combined), "| summary:", len(df_summary_combined))

meta: 179862 | summary: 4812

In [34]:
import pandas as pd

df = pd.read_csv("kosis_metadata_summary_enriched_final.csv")
df["top_category"] = df["category_path"].str.split(" > ").str[0]
print(df["top_category"].value_counts())

top_category
금융         2443
도소매ㆍ서비스    1988
무역ㆍ국제수지     311
정부ㆍ재정        70
Name: count, dtype: int64

In [35]:
df_validated.groupby("metric_domain")["mapping_status"].value_counts()

metric_domain  mapping_status
금융·금리          MAPPING_FAILED         39
               NOT_EVALUATED          20
               NEEDS_CONFIRMATION      1
무역             MAPPING_FAILED         83
               NOT_EVALUATED          48
               NEEDS_CONFIRMATION     13
물가             MAPPING_FAILED         10
               NOT_EVALUATED           6
               NEEDS_CONFIRMATION      2
보건·복지          MAPPING_FAILED          2
               NOT_EVALUATED           1
소득·임금          MAPPING_FAILED          2
               NOT_EVALUATED           1
소매·소비          MAPPING_FAILED        108
               NOT_EVALUATED          55
               NEEDS_CONFIRMATION      2
인구             MAPPING_FAILED          8
               NOT_EVALUATED           4
재정·조세          MAPPING_FAILED         12
               NOT_EVALUATED           7
               NEEDS_CONFIRMATION      2
Name: count, dtype: int64

In [36]:
import pandas as pd
df = pd.read_csv("kosis_validated_final.csv")

# 1순위 후보 중 NEEDS_CONFIRMATION만, 거리 낮은(그나마 유력한) 순으로
rank1_review = df[(df["candidate_rank"] == 1) & (df["mapping_status"] == "NEEDS_CONFIRMATION")].copy()
rank1_review["cosine_distance"] = rank1_review["match_reason"].str.extract(r"cosine_distance=([\d.]+)").astype(float)
rank1_review = rank1_review.sort_values("cosine_distance")

cols = ["claim_measurement_id", "metric_domain", "indicator", "value", "unit", "tbl_nm", "cosine_distance"]
rank1_review[cols].to_csv("review_priority.csv", index=False, encoding="utf-8-sig")
print(len(rank1_review), "건 - 거리 낮은 순으로 review_priority.csv 에 정렬해뒀습니다")
rank1_review[cols].head(20)

13 건 - 거리 낮은 순으로 review_priority.csv 에 정렬해뒀습니다

,claim_measurement_id,metric_domain,indicator,value,unit,tbl_nm,cosine_distance
153,B0020-s005-m1,무역,수출액 차이,5.235000e+09,달러,"국가별 수출액, 수입액",0.2802
147,B0020-s004-m1,무역,대미 수출액,1.277910e+11,달러,"국가별 수출액, 수입액",0.3126
141,B0020-s003-m1,무역,대중 수출액,1.330260e+11,달러,"국가별 수출액, 수입액",0.3173
156,B0020-s006-m1,무역,대중 수출액과 대미 수출액 간의 격차,8.900000e+08,달러,"국가별 수출액, 수입액",0.3301
159,B0020-s007-m2,무역,대중 수출액과 대미 수출액 간의 격차,8.940500e+10,달러,"국가별 수출액, 수입액",0.3324
162,B0020-s008-m2,무역,대미 수출액,1.000000e+11,달러,"국가별 수출액, 수입액",0.3366
165,B0020-s010-m1,무역,대중 수출액,1.168380e+11,달러,"국가별 수출액, 수입액",0.3419
168,B0020-s010-m3,무역,대중 수출액,1.629130e+11,달러,"국가별 수출액, 수입액",0.3419
387,B0020-s010-m2,무역,대중 수출액,1.000000e+11,달러,"국가별 수출액, 수입액",0.3419
423,B0048-s027-m1,금융·금리,원화 환율,1.453500e+03,원,한국은행 원화대출금,0.3700
48,B0011-s007-m1,소매·소비,영업이익,1.979420e+13,원,코스닥 상장사 수익현황,0.4097
345,B0011-s006-m1,소매·소비,영업이익,3.965310e+13,원,코스닥 상장사 수익현황,0.4097
327,B0046-s005-m1,재정·조세,순자금 운용액,2.980000e+13,원,가계대출 잔액 비중,0.4176

In [37]:
import pandas as pd
df = pd.read_csv("kosis_validated_final.csv")
rank1_review = df[(df["candidate_rank"] == 1) & (df["mapping_status"] == "NEEDS_CONFIRMATION")].copy()
rank1_review["cosine_distance"] = rank1_review["match_reason"].str.extract(r"cosine_distance=([\d.]+)").astype(float)

# 도메인별로 거리 가장 낮은(가장 유력한) 것 3개씩만
cols = ["claim_measurement_id", "indicator", "value", "unit", "tbl_nm", "cosine_distance"]
for domain, group in rank1_review.groupby("metric_domain"):
    print(f"=== {domain} ===")
    print(group.sort_values("cosine_distance")[cols].head(3).to_string(index=False))
    print()

=== 금융·금리 ===
claim_measurement_id indicator  value unit     tbl_nm  cosine_distance
       B0048-s027-m1     원화 환율 1453.5    원 한국은행 원화대출금             0.37

=== 무역 ===
claim_measurement_id indicator        value unit       tbl_nm  cosine_distance
       B0020-s005-m1    수출액 차이 5.235000e+09   달러 국가별 수출액, 수입액           0.2802
       B0020-s004-m1    대미 수출액 1.277910e+11   달러 국가별 수출액, 수입액           0.3126
       B0020-s003-m1    대중 수출액 1.330260e+11   달러 국가별 수출액, 수입액           0.3173

=== 소매·소비 ===
claim_measurement_id indicator        value unit       tbl_nm  cosine_distance
       B0011-s007-m1      영업이익 1.979420e+13    원 코스닥 상장사 수익현황           0.4097
       B0011-s006-m1      영업이익 3.965310e+13    원 코스닥 상장사 수익현황           0.4097

=== 재정·조세 ===
claim_measurement_id indicator        value unit     tbl_nm  cosine_distance
       B0046-s005-m1   순자금 운용액 2.980000e+13    원 가계대출 잔액 비중           0.4176

In [38]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive